import type { DibodevTradeQuizWording } from '~/core/types/DibodevTradeSoftwareQuiz'
import { NBSP } from '~/core/constants/typography'

export const BIKE_SHOP_QUIZ_WORDING_FR: DibodevTradeQuizWording = {
  numberLocale: 'fr-FR',
  quizName: `Quel logiciel pour votre atelier vélo${NBSP}?`,
  questions: [
    {
      id: 'team',
      title: `Combien de personnes à l’atelier et au magasin${NBSP}?`,
      helpText: 'Vous compris, avec les renforts du printemps.',
      leadMessageLabel: 'Équipe',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'personne', icon: null },
        { id: '2-4', label: '2 à 4', unit: 'personnes', icon: null },
        { id: '5-10', label: '5 à 10', unit: 'personnes', icon: null },
        { id: '10+', label: '+ de 10', unit: 'personnes', icon: null },
      ],
    },
    {
      id: 'sites',
      title: `Combien de magasins ou d’ateliers${NBSP}?`,
      helpText: 'Chaque adresse où vous réparez ou vendez des vélos.',
      leadMessageLabel: 'Magasins',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'magasin', icon: null },
        { id: '2-3', label: '2 ou 3', unit: 'magasins', icon: null },
        { id: '4+', label: '4 et +', unit: 'magasins', icon: null },
      ],
    },
    {
      id: 'scope',
      title: `Que faites-vous${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Activités',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'repair', label: 'Réparation et entretien', unit: '', icon: 'Wrench' },
        { id: 'sales', label: 'Vente de vélos neufs ou d’occasion', unit: '', icon: 'Store' },
        { id: 'ebike', label: 'Vélos à assistance électrique', unit: '', icon: 'BatteryCharging' },
        { id: 'rental', label: 'Location de vélos', unit: '', icon: 'CalendarCheck' },
      ],
    },
    {
      id: 'pains',
      title: `Qu’est-ce qui vous prend le plus de temps${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Ce qui prend du temps',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'booking', label: 'Prendre les rendez-vous d’atelier au téléphone', unit: '', icon: null },
        { id: 'tickets', label: 'Suivre les réparations en cours et prévenir les clients', unit: '', icon: null },
        { id: 'parts', label: 'Commander les pièces et suivre le stock', unit: '', icon: null },
        { id: 'till', label: 'Encaisser et faire les factures', unit: '', icon: null },
        { id: 'marking', label: 'Marquer les vélos vendus', unit: '', icon: null },
        { id: 'bonus', label: 'Monter les dossiers Bonus Réparation', unit: '', icon: null },
        { id: 'history', label: 'Retrouver l’historique d’un vélo ou d’un client', unit: '', icon: null },
        { id: 'rental', label: 'Gérer les locations et les cautions', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: `Utilisez-vous déjà un logiciel d’atelier ou de caisse${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Logiciel actuel',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'Non, un cahier, Excel ou une caisse seule', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Oui, mais il ne colle pas à notre façon de travailler', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Oui, et il nous convient', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: `Qu’est-ce qui compte le plus pour vous${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Priorité',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Démarrer vite, avec un petit budget', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'Un outil simple pour les mécaniciens', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'Un outil qui suit nos forfaits, nos délais et nos magasins',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        {
          id: 'ownership',
          label: 'Ne plus dépendre d’un abonnement et garder nos données',
          unit: '',
          icon: 'KeyRound',
        },
      ],
    },
  ],
  conjunction: 'et',
  priceRangeTemplate: `{min} à {max}${NBSP}€`,
  weeksRangeTemplate: '{min} à {max} semaines',
  recapTeamWords: {
    '1': 'une seule personne',
    '2-4': '2 à 4 personnes',
    '5-10': '5 à 10 personnes',
    '10+': 'plus de 10 personnes',
  },
  recapSitesWords: { '1': 'un seul magasin', '2-3': '2 ou 3 magasins', '4+': '4 magasins ou plus' },
  recapScopeWords: { repair: 'réparation', sales: 'vente', ebike: 'vélos électriques', rental: 'location' },
  recapScopeTemplate: '{items}',
  complementPainWords: {
    booking: 'les rendez-vous',
    tickets: 'le suivi des réparations',
    parts: 'les pièces',
    till: 'l’encaissement',
    marking: 'le marquage',
    bonus: 'le Bonus Réparation',
    history: 'l’historique des vélos',
    rental: 'les locations',
  },
  features: {
    booking: 'La prise de rendez-vous d’atelier en ligne, sur votre site, selon la place réelle des mécaniciens',
    tickets: 'Des fiches atelier suivies de l’accueil à la remise, avec un SMS quand le vélo est prêt',
    parts: 'Les pièces commandées pour chaque réparation, et le stock mis à jour à la pose',
    till: 'Des factures créées depuis la fiche atelier, envoyées vers votre caisse ou votre comptabilité',
    marking: 'Le numéro de marquage enregistré avec chaque vélo vendu, et la fiche du propriétaire prête',
    bonus: 'Les dossiers Bonus Réparation préparés depuis la fiche atelier (montant, photos, facture)',
    history: 'L’historique de chaque vélo et de chaque client, retrouvé en quelques secondes',
    rental: 'Le planning des locations, avec la caution et l’état du vélo au départ et au retour',
    ebike: 'Les batteries et moteurs suivis par numéro de série, avec leurs garanties',
    multiSite: 'Le stock et le planning de chaque magasin, et les transferts d’un magasin à l’autre',
  },
  checks: {
    primary: `La caisse est-elle sécurisée, avec un certificat ou une attestation de l’éditeur${NBSP}?`,
    booking: `Vos clients peuvent-ils réserver un créneau d’atelier en ligne, sur votre site${NBSP}?`,
    tickets: `Le client est-il prévenu par SMS ou e-mail quand son vélo est prêt${NBSP}?`,
    parts: `Le stock de pièces se met-il à jour quand une pièce est posée${NBSP}?`,
    till: `Les factures partent-elles de la fiche atelier, sans ressaisie${NBSP}?`,
    marking: `Le logiciel garde-t-il le numéro de marquage de chaque vélo vendu${NBSP}?`,
    bonus: `Aide-t-il à monter les dossiers Bonus Réparation${NBSP}?`,
    history: `Retrouve-t-on l’historique d’un vélo par son numéro de cadre ou de marquage${NBSP}?`,
    rental: `Gère-t-il les locations, les cautions et l’état des vélos au retour${NBSP}?`,
    ebike: `Peut-on suivre les batteries et moteurs (numéro de série, garantie)${NBSP}?`,
    export: `Pouvez-vous exporter vos données (clients, vélos, ventes) si vous changez de logiciel${NBSP}?`,
  },
  market: {
    eyebrow: 'Budget à prévoir',
    priceRange: `9 à 150${NBSP}€`,
    priceSuffix: 'par mois, selon les modules et le nombre de magasins',
    priceExamples: [
      { label: 'Epsylon', value: `9 à 89${NBSP}€/mois` },
      { label: 'Atelier Vélo+', value: `199${NBSP}€/an` },
      { label: 'CycleSoftware', value: `70${NBSP}€ HT/mois` },
      { label: 'Shifter', value: `69 à 148${NBSP}€ HT/mois` },
    ],
    footnote: `Atelier Vélo+ passe à 359${NBSP}€ par an avec la prise de rendez-vous en ligne. CycleSoftware ajoute 70${NBSP}€ HT par mois pour plusieurs magasins, avec un engagement d’un an.`,
    footnoteLink: { label: 'Voir tous les prix', href: '#logiciels' },
    adviceTitle: 'À vérifier avant de choisir',
    disclaimer: 'Prix publics relevés le 29 septembre 2026.',
    ctaLabel: 'Demander un avis gratuit',
    leadFormTitle: 'Un avis gratuit pour choisir votre logiciel',
    leadFormIntro: `Je vous réponds sous 24${NBSP}h pour en parler, au téléphone ou en visio. Vos réponses au test sont jointes à votre message.`,
    leadBudget: `Logiciel du marché, 9 à 150${NBSP}€ par mois`,
  },
  project: {
    eyebrow: 'Ordre de prix, au forfait',
    durationLabel: 'Délai',
    maintenanceLabel: 'Maintenance',
    maintenanceValue: `100 à 300${NBSP}€/mois`,
    complementFootnote: 'Payé une seule fois, en plus de votre abonnement actuel.',
    customFootnote: `Payé une seule fois${NBSP}: l’outil et son code vous appartiennent.`,
    adviceTitle: 'À prévoir en priorité',
    disclaimer: 'Résultat indicatif. Le prix définitif est fixé dans le devis.',
    ctaLabel: 'Recevoir mon estimation',
    leadFormTitle: 'Recevoir mon estimation détaillée',
    leadFormIntro: `Je vous réponds sous 24${NBSP}h avec de premières pistes et un budget plus précis. Vos réponses au test sont jointes à votre message.`,
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'complément sur mesure',
    customKind: 'outil sur mesure',
  },
  results: {
    custom: {
      title: 'Un outil sur mesure pour votre atelier',
      explanation:
        'À votre taille et avec vos propres règles (forfaits, délais, magasins), les logiciels du marché vous obligent à vous adapter à eux. Un outil conçu pour vous suit votre organisation et vous appartient. Votre caisse sécurisée reste en place, reliée à l’outil.',
    },
    complement: {
      title: 'Gardez votre logiciel, ajoutez un complément sur mesure',
      explanation:
        'Votre logiciel fait le travail de base, inutile d’en changer. Un petit outil branché dessus peut régler ce qui vous prend encore du temps{pains}.',
      painsTemplate: `${NBSP}: {list}`,
    },
    solo: {
      title: 'Un logiciel du marché vous suffit',
      explanation: `Seul à l’atelier, un logiciel à moins de 20${NBSP}€ par mois couvre l’essentiel${NBSP}: rendez-vous, fiches atelier, caisse et factures. Un outil sur mesure ne serait pas rentable.`,
      keepCurrentSentence: ' Si le vôtre vous convient, gardez-le.',
    },
    market: {
      title: 'Un logiciel du marché vous suffit pour l’instant',
      explanation: `À votre taille, les logiciels pour magasins de vélos couvrent l’essentiel${NBSP}: rendez-vous, fiches atelier, stock, caisse et factures. Un outil sur mesure vous coûterait plus qu’il ne vous ferait gagner aujourd’hui.`,
      unfitSentence:
        ' Si le vôtre ne vous convient pas, comparez-en deux ou trois avec les points ci-dessous avant d’en changer.',
    },
  },
}
