import type { DibodevTradeQuizWording } from '~/core/types/DibodevTradeSoftwareQuiz'
import { NBSP } from '~/core/constants/typography'

export const BIKE_SHOP_QUIZ_WORDING_ES: DibodevTradeQuizWording = {
  numberLocale: 'es-ES',
  quizName: '¿Qué software para tu taller de bicicletas?',
  questions: [
    {
      id: 'team',
      title: '¿Cuántas personas trabajan en el taller y en la tienda?',
      helpText: 'Contándote a ti, con los refuerzos de primavera.',
      leadMessageLabel: 'Equipo',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'persona', icon: null },
        { id: '2-4', label: '2 a 4', unit: 'personas', icon: null },
        { id: '5-10', label: '5 a 10', unit: 'personas', icon: null },
        { id: '10+', label: '+ de 10', unit: 'personas', icon: null },
      ],
    },
    {
      id: 'sites',
      title: '¿Cuántas tiendas o talleres?',
      helpText: 'Cada dirección donde reparas o vendes bicicletas.',
      leadMessageLabel: 'Tiendas',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'tienda', icon: null },
        { id: '2-3', label: '2 o 3', unit: 'tiendas', icon: null },
        { id: '4+', label: '4 o más', unit: 'tiendas', icon: null },
      ],
    },
    {
      id: 'scope',
      title: '¿A qué te dedicas?',
      helpText: '',
      leadMessageLabel: 'Actividades',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'repair', label: 'Reparación y mantenimiento', unit: '', icon: 'Wrench' },
        { id: 'sales', label: 'Venta de bicicletas nuevas o de segunda mano', unit: '', icon: 'Store' },
        { id: 'ebike', label: 'Bicicletas eléctricas', unit: '', icon: 'BatteryCharging' },
        { id: 'rental', label: 'Alquiler de bicicletas', unit: '', icon: 'CalendarCheck' },
      ],
    },
    {
      id: 'pains',
      title: '¿Qué es lo que más tiempo te quita?',
      helpText: '',
      leadMessageLabel: 'Lo que quita tiempo',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'booking', label: 'Dar citas de taller por teléfono', unit: '', icon: null },
        { id: 'tickets', label: 'Seguir las reparaciones en curso y avisar a los clientes', unit: '', icon: null },
        { id: 'parts', label: 'Pedir las piezas y seguir el stock', unit: '', icon: null },
        { id: 'till', label: 'Cobrar y hacer las facturas', unit: '', icon: null },
        { id: 'marking', label: 'Marcar las bicicletas vendidas', unit: '', icon: null },
        { id: 'bonus', label: 'Preparar los expedientes del bono de reparación', unit: '', icon: null },
        { id: 'history', label: 'Encontrar el historial de una bicicleta o de un cliente', unit: '', icon: null },
        { id: 'rental', label: 'Gestionar los alquileres y las fianzas', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: '¿Ya usas un software de taller o de caja?',
      helpText: '',
      leadMessageLabel: 'Software actual',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'No, un cuaderno, Excel o solo una caja', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Sí, pero no se adapta a nuestra forma de trabajar', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Sí, y nos va bien', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: '¿Qué es lo más importante para ti?',
      helpText: '',
      leadMessageLabel: 'Prioridad',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Empezar rápido, con poco presupuesto', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'Una herramienta sencilla para los mecánicos', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'Una herramienta que siga nuestras tarifas, plazos y tiendas',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        {
          id: 'ownership',
          label: 'Dejar de depender de una suscripción y conservar nuestros datos',
          unit: '',
          icon: 'KeyRound',
        },
      ],
    },
  ],
  conjunction: 'y',
  priceRangeTemplate: `{min} a {max}${NBSP}€`,
  weeksRangeTemplate: '{min} a {max} semanas',
  recapTeamWords: {
    '1': 'una sola persona',
    '2-4': '2 a 4 personas',
    '5-10': '5 a 10 personas',
    '10+': 'más de 10 personas',
  },
  recapSitesWords: { '1': 'una sola tienda', '2-3': '2 o 3 tiendas', '4+': '4 tiendas o más' },
  recapScopeWords: { repair: 'reparación', sales: 'venta', ebike: 'bicicletas eléctricas', rental: 'alquiler' },
  recapScopeTemplate: '{items}',
  complementPainWords: {
    booking: 'las citas',
    tickets: 'el seguimiento de las reparaciones',
    parts: 'las piezas',
    till: 'el cobro',
    marking: 'el marcado',
    bonus: 'el bono de reparación',
    history: 'el historial de las bicicletas',
    rental: 'los alquileres',
  },
  features: {
    booking: 'Citas de taller en línea, en tu web, según la disponibilidad real de los mecánicos',
    tickets: 'Fichas de taller seguidas desde la recepción hasta la entrega, con un SMS cuando la bici está lista',
    parts: 'Las piezas pedidas para cada reparación, y el stock actualizado al montarlas',
    till: 'Facturas creadas desde la ficha de taller, enviadas a tu caja o a tu contabilidad',
    marking: 'El número de marcado guardado con cada bicicleta vendida, y los datos del propietario listos',
    bonus: 'Los expedientes del bono de reparación preparados desde la ficha de taller (importe, fotos, factura)',
    history: 'El historial de cada bicicleta y de cada cliente, en unos segundos',
    rental: 'La agenda de alquileres, con la fianza y el estado de la bici a la salida y a la vuelta',
    ebike: 'Las baterías y los motores seguidos por número de serie, con sus garantías',
    multiSite: 'El stock y la agenda de cada tienda, y los traslados de una tienda a otra',
  },
  checks: {
    primary: '¿La caja es segura, con un certificado o una declaración del editor, como exige la ley francesa?',
    booking: '¿Tus clientes pueden reservar una cita de taller en línea, en tu web?',
    tickets: '¿Se avisa al cliente por SMS o correo cuando su bici está lista?',
    parts: '¿El stock de piezas se actualiza al montar una pieza?',
    till: '¿Las facturas salen de la ficha de taller, sin volver a escribir nada?',
    marking: '¿El software guarda el número de marcado de cada bicicleta vendida?',
    bonus: '¿Ayuda a preparar los expedientes del bono de reparación?',
    history: '¿Se encuentra el historial de una bici por su número de cuadro o de marcado?',
    rental: '¿Gestiona los alquileres, las fianzas y el estado de las bicis a la vuelta?',
    ebike: '¿Se pueden seguir las baterías y los motores (número de serie, garantía)?',
    export: '¿Puedes exportar tus datos (clientes, bicicletas, ventas) si cambias de software?',
  },
  market: {
    eyebrow: 'Presupuesto a prever',
    priceRange: `9 a 150${NBSP}€`,
    priceSuffix: 'al mes, según los módulos y el número de tiendas',
    priceExamples: [
      { label: 'Epsylon', value: `9 a 89${NBSP}€/mes` },
      { label: 'Atelier Vélo+', value: `199${NBSP}€/año` },
      { label: 'CycleSoftware', value: `70${NBSP}€/mes sin IVA` },
      { label: 'Shifter', value: `69 a 148${NBSP}€/mes sin IVA` },
    ],
    footnote: `Atelier Vélo+ sube a 359${NBSP}€ al año con las citas en línea. CycleSoftware añade 70${NBSP}€ sin IVA al mes para varias tiendas, con un compromiso de un año.`,
    footnoteLink: { label: 'Ver todos los precios', href: '#programas' },
    adviceTitle: 'Qué comprobar antes de elegir',
    disclaimer: 'Precios públicos consultados el 29 de septiembre de 2026.',
    ctaLabel: 'Pedir consejo gratis',
    leadFormTitle: 'Un consejo gratuito para elegir tu software',
    leadFormIntro: `Te respondo en 24${NBSP}h para hablarlo, por teléfono o videollamada. Tus respuestas al test se adjuntan a tu mensaje.`,
    leadBudget: `Software del mercado, 9 a 150${NBSP}€ al mes`,
  },
  project: {
    eyebrow: 'Orden de precio, a precio cerrado',
    durationLabel: 'Plazo',
    maintenanceLabel: 'Mantenimiento',
    maintenanceValue: `100 a 300${NBSP}€/mes`,
    complementFootnote: 'Se paga una sola vez, además de tu suscripción actual.',
    customFootnote: 'Se paga una sola vez: la herramienta y su código son tuyos.',
    adviceTitle: 'Qué prever primero',
    disclaimer: 'Resultado orientativo. El precio final se fija en el presupuesto.',
    ctaLabel: 'Recibir mi estimación',
    leadFormTitle: 'Recibir mi estimación detallada',
    leadFormIntro: `Te respondo en 24${NBSP}h con primeras ideas y un presupuesto más preciso. Tus respuestas al test se adjuntan a tu mensaje.`,
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'complemento a medida',
    customKind: 'herramienta a medida',
  },
  results: {
    custom: {
      title: 'Una herramienta a medida para tu taller',
      explanation:
        'Con tu tamaño y tus propias reglas (tarifas, plazos, tiendas), los programas del mercado te obligan a adaptarte a ellos. Una herramienta diseñada para ti sigue tu forma de trabajar y es tuya. Tu caja segura se queda, conectada a la herramienta.',
    },
    complement: {
      title: 'Conserva tu software y añade un complemento a medida',
      explanation:
        'Tu software hace el trabajo básico, no hace falta cambiarlo. Una pequeña herramienta conectada a él puede resolver lo que aún te quita tiempo{pains}.',
      painsTemplate: ': {list}',
    },
    solo: {
      title: 'Te basta con un software del mercado',
      explanation: `Si trabajas solo en el taller, un software de menos de 20${NBSP}€ al mes cubre lo esencial: citas, fichas de taller, caja y facturas. Una herramienta a medida no sería rentable.`,
      keepCurrentSentence: ' Si el tuyo te va bien, consérvalo.',
    },
    market: {
      title: 'Por ahora te basta con un software del mercado',
      explanation:
        'Con tu tamaño, los programas para tiendas de bicicletas cubren lo esencial: citas, fichas de taller, stock, caja y facturas. Una herramienta a medida te costaría hoy más de lo que te haría ganar.',
      unfitSentence: ' Si el tuyo no te convence, compara dos o tres con los puntos de abajo antes de cambiar.',
    },
  },
}
