import type { DibodevTradeQuizWording } from '~/core/types/DibodevTradeSoftwareQuiz'

export const BIKE_SHOP_QUIZ_WORDING_EN: DibodevTradeQuizWording = {
  numberLocale: 'en-GB',
  quizName: 'Which software for your bike shop?',
  questions: [
    {
      id: 'team',
      title: 'How many people work in the workshop and the shop?',
      helpText: 'Including you, and the extra hands of spring.',
      leadMessageLabel: 'Team',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'person', icon: null },
        { id: '2-4', label: '2 to 4', unit: 'people', icon: null },
        { id: '5-10', label: '5 to 10', unit: 'people', icon: null },
        { id: '10+', label: '10+', unit: 'people', icon: null },
      ],
    },
    {
      id: 'sites',
      title: 'How many shops or workshops?',
      helpText: 'Each address where you repair or sell bikes.',
      leadMessageLabel: 'Shops',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'shop', icon: null },
        { id: '2-3', label: '2 or 3', unit: 'shops', icon: null },
        { id: '4+', label: '4+', unit: 'shops', icon: null },
      ],
    },
    {
      id: 'scope',
      title: 'What do you do?',
      helpText: '',
      leadMessageLabel: 'Activities',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'repair', label: 'Repairs and servicing', unit: '', icon: 'Wrench' },
        { id: 'sales', label: 'New or used bike sales', unit: '', icon: 'Store' },
        { id: 'ebike', label: 'E-bikes', unit: '', icon: 'BatteryCharging' },
        { id: 'rental', label: 'Bike rental', unit: '', icon: 'CalendarCheck' },
      ],
    },
    {
      id: 'pains',
      title: 'What takes up most of your time?',
      helpText: '',
      leadMessageLabel: 'Time-consuming tasks',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'booking', label: 'Taking workshop bookings over the phone', unit: '', icon: null },
        { id: 'tickets', label: 'Following repairs in progress and updating customers', unit: '', icon: null },
        { id: 'parts', label: 'Ordering parts and tracking stock', unit: '', icon: null },
        { id: 'till', label: 'Taking payments and writing invoices', unit: '', icon: null },
        { id: 'marking', label: 'Marking the bikes you sell', unit: '', icon: null },
        { id: 'bonus', label: 'Filing repair bonus claims', unit: '', icon: null },
        { id: 'history', label: 'Finding the history of a bike or a customer', unit: '', icon: null },
        { id: 'rental', label: 'Managing rentals and deposits', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: 'Do you already use workshop or till software?',
      helpText: '',
      leadMessageLabel: 'Current software',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'No: a notebook, Excel or just a till', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Yes, but it does not fit the way we work', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Yes, and it suits us', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: 'What matters most to you?',
      helpText: '',
      leadMessageLabel: 'Priority',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Getting started quickly, on a small budget', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'A simple tool for the mechanics', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'A tool that follows our service packages, lead times and shops',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        { id: 'ownership', label: 'No more subscription, and keeping our data', unit: '', icon: 'KeyRound' },
      ],
    },
  ],
  conjunction: 'and',
  priceRangeTemplate: '€{min} to €{max}',
  weeksRangeTemplate: '{min} to {max} weeks',
  recapTeamWords: { '1': 'one person', '2-4': '2 to 4 people', '5-10': '5 to 10 people', '10+': 'more than 10 people' },
  recapSitesWords: { '1': 'one shop', '2-3': '2 or 3 shops', '4+': '4 shops or more' },
  recapScopeWords: { repair: 'repairs', sales: 'sales', ebike: 'e-bikes', rental: 'rental' },
  recapScopeTemplate: '{items}',
  complementPainWords: {
    booking: 'bookings',
    tickets: 'repair tracking',
    parts: 'parts',
    till: 'payments',
    marking: 'bike marking',
    bonus: 'the repair bonus',
    history: 'bike history',
    rental: 'rentals',
  },
  features: {
    booking: 'Online workshop booking on your website, based on the mechanics’ real availability',
    tickets: 'Repair tickets followed from drop-off to pick-up, with a text message when the bike is ready',
    parts: 'Parts ordered for each repair, and stock updated when they are fitted',
    till: 'Invoices created from the repair ticket, sent to your till or your accounting software',
    marking: 'The marking number saved with each bike sold, and the owner’s details ready',
    bonus: 'Repair bonus claims prepared from the repair ticket (amount, photos, invoice)',
    history: 'The history of every bike and every customer, found in seconds',
    rental: 'The rental schedule, with the deposit and the bike’s condition on departure and return',
    ebike: 'Batteries and motors tracked by serial number, with their warranties',
    multiSite: 'The stock and schedule of each shop, and transfers from one shop to another',
  },
  checks: {
    primary: 'Is the till secure, with a certificate or a statement from the publisher, as French law requires?',
    booking: 'Can your customers book a workshop slot online, on your website?',
    tickets: 'Is the customer told by text or email when their bike is ready?',
    parts: 'Is the parts stock updated when a part is fitted?',
    till: 'Are invoices created from the repair ticket, with no retyping?',
    marking: 'Does the software keep the marking number of each bike sold?',
    bonus: 'Does it help you file repair bonus claims?',
    history: 'Can you find a bike’s history from its frame or marking number?',
    rental: 'Does it handle rentals, deposits and the bikes’ condition on return?',
    ebike: 'Can you track batteries and motors (serial number, warranty)?',
    export: 'Can you export your data (customers, bikes, sales) if you change software?',
  },
  market: {
    eyebrow: 'Budget to plan',
    priceRange: '€9 to €150',
    priceSuffix: 'per month, depending on modules and number of shops',
    priceExamples: [
      { label: 'Epsylon', value: '€9 to €89/month' },
      { label: 'Atelier Vélo+', value: '€199/year' },
      { label: 'CycleSoftware', value: '€70/month excl. VAT' },
      { label: 'Shifter', value: '€69 to €148/month excl. VAT' },
    ],
    footnote:
      'Atelier Vélo+ goes up to €359 per year with online booking. CycleSoftware adds €70 excl. VAT per month for several shops, with a one-year commitment.',
    footnoteLink: { label: 'See all prices', href: '#software' },
    adviceTitle: 'What to check before choosing',
    disclaimer: 'Public prices checked on 29 September 2026.',
    ctaLabel: 'Get free advice',
    leadFormTitle: 'Free advice to choose your software',
    leadFormIntro:
      'I reply within 24 hours to talk it through, by phone or video call. Your test answers are attached to your message.',
    leadBudget: 'Off-the-shelf software, €9 to €150 per month',
  },
  project: {
    eyebrow: 'Price range, fixed price',
    durationLabel: 'Timeline',
    maintenanceLabel: 'Maintenance',
    maintenanceValue: '€100 to €300/month',
    complementFootnote: 'Paid once, on top of your current subscription.',
    customFootnote: 'Paid once: the tool and its code belong to you.',
    adviceTitle: 'What to plan first',
    disclaimer: 'Indicative result. The final price is set in the quote.',
    ctaLabel: 'Get my estimate',
    leadFormTitle: 'Get my detailed estimate',
    leadFormIntro:
      'I reply within 24 hours with first ideas and a more precise budget. Your test answers are attached to your message.',
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'custom extension',
    customKind: 'custom tool',
  },
  results: {
    custom: {
      title: 'A custom tool for your bike shop',
      explanation:
        'At your size and with your own rules (service packages, lead times, shops), off-the-shelf software makes you adapt to it. A tool designed for you follows the way you work and belongs to you. Your secure till stays in place, connected to the tool.',
    },
    complement: {
      title: 'Keep your software and add a custom extension',
      explanation:
        'Your software does the basics, there is no need to change it. A small tool plugged into it can handle what still takes up your time{pains}.',
      painsTemplate: ': {list}',
    },
    solo: {
      title: 'Off-the-shelf software is enough for you',
      explanation:
        'Working alone in the workshop, software under €20 a month covers the essentials: bookings, repair tickets, till and invoices. A custom tool would not pay off.',
      keepCurrentSentence: ' If yours suits you, keep it.',
    },
    market: {
      title: 'Off-the-shelf software is enough for now',
      explanation:
        'At your size, bike shop software covers the essentials: bookings, repair tickets, stock, till and invoices. A custom tool would cost you more than it would save you today.',
      unfitSentence: ' If yours does not suit you, compare two or three with the points below before switching.',
    },
  },
}
