import type { DibodevDrivingSchoolQuizWording } from '~/core/types/DibodevDrivingSchoolSoftwareQuiz'

export const DRIVING_SCHOOL_QUIZ_WORDING_EN: DibodevDrivingSchoolQuizWording = {
  numberLocale: 'en-GB',
  quizName: 'Which software for your driving school?',
  questions: [
    {
      id: 'instructors',
      title: 'How many instructors work at your driving school?',
      helpText: 'Including you, if you also give lessons.',
      leadMessageLabel: 'Instructors',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'instructor', icon: null },
        { id: '2-4', label: '2 to 4', unit: 'instructors', icon: null },
        { id: '5-10', label: '5 to 10', unit: 'instructors', icon: null },
        { id: '10+', label: '10+', unit: 'instructors', icon: null },
      ],
    },
    {
      id: 'agencies',
      title: 'How many branches?',
      helpText: 'Each location where your students sign up or meet their instructor.',
      leadMessageLabel: 'Branches',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'branch', icon: null },
        { id: '2-3', label: '2 or 3', unit: 'branches', icon: null },
        { id: '4+', label: '4+', unit: 'branches', icon: null },
      ],
    },
    {
      id: 'booking',
      title: 'How do your students book their lessons today?',
      helpText: '',
      leadMessageLabel: 'Booking',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'phone', label: 'By phone or at the office', unit: '', icon: 'Phone' },
        { id: 'messages', label: 'By text message or WhatsApp', unit: '', icon: 'MessageCircle' },
        { id: 'online', label: 'Online, through software or an app', unit: '', icon: 'Laptop' },
      ],
    },
    {
      id: 'pains',
      title: 'What takes up most of your time?',
      helpText: '',
      leadMessageLabel: 'Time-consuming tasks',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'planning', label: 'Scheduling instructors and cars', unit: '', icon: null },
        { id: 'noshow', label: 'Last-minute cancellations', unit: '', icon: null },
        { id: 'hours', label: 'Tracking hours and lesson packages', unit: '', icon: null },
        { id: 'payments', label: 'Instalment payments and reminders', unit: '', icon: null },
        { id: 'cpf', label: 'Funded training (CPF, employer)', unit: '', icon: null },
        { id: 'progress', label: 'The logbook and student progress', unit: '', icon: null },
        { id: 'exams', label: 'Test slots and students ready for the test', unit: '', icon: null },
        { id: 'questions', label: 'Questions from students and parents', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: 'Do you already use management software?',
      helpText: '',
      leadMessageLabel: 'Current software',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'No: a diary, paper or Excel', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Yes, but it does not fit the way we work', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Yes, and it suits us', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: 'What matters most to you?',
      helpText: '',
      leadMessageLabel: 'Priority',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Getting started quickly, on a small budget', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'A simple tool the instructors will actually use', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'A tool that follows our packages, prices and branches',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        { id: 'ownership', label: 'No more subscription, and keeping our data', unit: '', icon: 'KeyRound' },
      ],
    },
  ],
  conjunction: 'and',
  priceRangeTemplate: '€{min} to €{max}',
  weeksRangeTemplate: '{min} to {max} weeks',
  recapInstructorWords: {
    '1': 'one instructor',
    '2-4': '2 to 4 instructors',
    '5-10': '5 to 10 instructors',
    '10+': 'more than 10 instructors',
  },
  recapAgencyWords: { '1': 'one branch', '2-3': '2 or 3 branches', '4+': '4 branches or more' },
  recapBookingWords: { phone: 'by phone', messages: 'by text or WhatsApp', online: 'online' },
  recapBookingTemplate: 'bookings {channels}',
  complementPainWords: {
    planning: 'scheduling',
    noshow: 'cancellations',
    hours: 'hour tracking',
    payments: 'payments',
    cpf: 'funding',
    progress: 'the logbook',
    exams: 'test slots',
    questions: 'students’ questions',
  },
  featuresByPain: {
    planning: 'A shared schedule of instructors and cars, with no double bookings',
    noshow: 'Reminders the day before, the 48-working-hour rule of your contract and a waiting list',
    hours: 'Each student’s hours and package balance, visible on their side',
    payments: 'Payment schedules and automatic reminders',
    cpf: 'Tracking of funded training: co-funding, remaining cost and deadlines',
    progress: 'The student’s logbook linked to the schedule, skill by skill',
    exams: 'The list of students ready for the test and tracking of test slots',
    questions: 'A student area: bookings, remaining hours, documents and payments',
  },
  checksByPain: {
    planning: 'Does the scheduler handle cars as well as instructors?',
    noshow: 'Are text reminders included, or billed separately?',
    hours: 'Can students see their remaining hours and package?',
    payments: 'Can students pay in instalments, with automatic reminders?',
    cpf: 'Is the software connected to EDOF, the platform for CPF-funded training?',
    exams: 'Does the software help you spot students ready for the test?',
    questions: 'Is there a student app or student area?',
  },
  logbookCheck: 'Is the digital logbook included, and sent to the French State through the official interface?',
  dataExportCheck: 'Can you export your data (students, hours, payments) if you change software?',
  onlineBookingFeature: 'Online lesson booking, 24/7, from your own website',
  singlePlanningFeature: 'All bookings in a single schedule, whatever the channel',
  agenciesFeature: 'A view per branch, and an overall view for management',
  market: {
    eyebrow: 'Budget to plan',
    priceRange: 'Free to €249',
    priceSuffix: 'per month excl. VAT, for one branch',
    priceExamples: [
      { label: 'Ma Gestion Zen', value: '€39/month' },
      { label: 'Drivup', value: 'from €45/month' },
      { label: 'Kréno 2', value: '€49/month' },
      { label: 'GestAuto-École', value: '€79/month' },
      { label: 'Klaxo', value: 'from €99/month' },
    ],
    footnote:
      'Drivea and the basic plan of rdv360 are free: check that they handle the digital logbook. Rapido, Elgéaweb and AGX are on quote.',
    footnoteLink: { label: 'See all prices', href: '#software' },
    adviceTitle: 'What to check before choosing',
    disclaimer: 'Public prices excluding VAT, checked at the end of September 2026.',
    ctaLabel: 'Get free advice',
    leadFormTitle: 'Free advice to choose your software',
    leadFormIntro:
      'I reply within 24 hours to talk it through, by phone or video call. Your test answers are attached to your message.',
    leadBudget: 'Off-the-shelf software, free to €249 excl. VAT per month',
  },
  project: {
    eyebrow: 'Price range, fixed price',
    durationLabel: 'Timeline',
    maintenanceLabel: 'Maintenance',
    maintenanceValue: '€100 to €300/month',
    complementFootnote: 'Paid once, on top of your current subscription.',
    customFootnote: 'Paid once: the tool and its code belong to you.',
    adviceTitle: 'What to plan first',
    disclaimer: 'Indicative result. The final price is set in the quote.',
    ctaLabel: 'Get my estimate',
    leadFormTitle: 'Get my detailed estimate',
    leadFormIntro:
      'I reply within 24 hours with first ideas and a more precise budget. Your test answers are attached to your message.',
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'custom extension',
    customKind: 'custom tool',
  },
  results: {
    custom: {
      title: 'A custom tool for your driving school',
      explanation:
        'At your size and with your own rules, off-the-shelf software makes you adapt to it. A tool designed for you follows the way you work and belongs to you. The digital logbook, ANTS and RdvPermis stay in compliant software, connected to the tool.',
    },
    complement: {
      title: 'Keep your software and add a custom extension',
      explanation:
        'Your software does the basics, there is no need to change it. A small tool plugged into it can handle what still takes up your time{pains}.',
      painsTemplate: ': {list}',
    },
    solo: {
      title: 'Off-the-shelf software is enough for you',
      explanation:
        'For a single instructor, software under €50 a month covers the essentials: scheduling, online booking, hour tracking and the digital logbook. A custom tool would not pay off.',
      keepCurrentSentence: ' If yours suits you, keep it.',
    },
    market: {
      title: 'Off-the-shelf software is enough for now',
      explanation:
        'At your size, the driving school software on the market covers the essentials: scheduling, online booking, hour tracking and the digital logbook. A custom tool would cost you more than it would save you today.',
      unfitSentence: ' If yours does not suit you, compare two or three with the points below before switching.',
    },
  },
}
