import type { DibodevDrivingSchoolQuizWording } from '~/core/types/DibodevDrivingSchoolSoftwareQuiz'
import { NBSP } from '~/core/constants/typography'

export const DRIVING_SCHOOL_QUIZ_WORDING_ES: DibodevDrivingSchoolQuizWording = {
  numberLocale: 'es-ES',
  quizName: '¿Qué software para tu autoescuela?',
  questions: [
    {
      id: 'instructors',
      title: '¿Cuántos profesores trabajan en tu autoescuela?',
      helpText: 'Contándote a ti, si también das clases.',
      leadMessageLabel: 'Profesores',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'profesor', icon: null },
        { id: '2-4', label: '2 a 4', unit: 'profesores', icon: null },
        { id: '5-10', label: '5 a 10', unit: 'profesores', icon: null },
        { id: '10+', label: '+ de 10', unit: 'profesores', icon: null },
      ],
    },
    {
      id: 'agencies',
      title: '¿Cuántos centros tienes?',
      helpText: 'Cada local donde tus alumnos se inscriben o quedan con su profesor.',
      leadMessageLabel: 'Centros',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'centro', icon: null },
        { id: '2-3', label: '2 o 3', unit: 'centros', icon: null },
        { id: '4+', label: '4 o +', unit: 'centros', icon: null },
      ],
    },
    {
      id: 'booking',
      title: '¿Cómo reservan hoy tus alumnos sus clases?',
      helpText: '',
      leadMessageLabel: 'Reservas',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'phone', label: 'Por teléfono o en la oficina', unit: '', icon: 'Phone' },
        { id: 'messages', label: 'Por SMS o WhatsApp', unit: '', icon: 'MessageCircle' },
        { id: 'online', label: 'En línea, con un programa o una app', unit: '', icon: 'Laptop' },
      ],
    },
    {
      id: 'pains',
      title: '¿Qué es lo que más tiempo te quita?',
      helpText: '',
      leadMessageLabel: 'Lo que quita tiempo',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'planning', label: 'La agenda de profesores y coches', unit: '', icon: null },
        { id: 'noshow', label: 'Las cancelaciones de última hora', unit: '', icon: null },
        { id: 'hours', label: 'El seguimiento de horas y bonos', unit: '', icon: null },
        { id: 'payments', label: 'Los pagos a plazos y los recordatorios', unit: '', icon: null },
        { id: 'cpf', label: 'La formación financiada (CPF, empresa)', unit: '', icon: null },
        { id: 'progress', label: 'El libro de aprendizaje y el progreso de los alumnos', unit: '', icon: null },
        { id: 'exams', label: 'Las plazas de examen y los alumnos listos', unit: '', icon: null },
        { id: 'questions', label: 'Las preguntas de alumnos y padres', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: '¿Ya usas un programa de gestión?',
      helpText: '',
      leadMessageLabel: 'Programa actual',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'No: una agenda, papel o Excel', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Sí, pero no encaja con nuestra forma de trabajar', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Sí, y nos va bien', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: '¿Qué es lo más importante para ti?',
      helpText: '',
      leadMessageLabel: 'Prioridad',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Empezar rápido, con poco presupuesto', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'Una herramienta sencilla que los profesores adopten', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'Una herramienta que siga nuestros bonos, tarifas y centros',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        {
          id: 'ownership',
          label: 'No depender de una suscripción y conservar nuestros datos',
          unit: '',
          icon: 'KeyRound',
        },
      ],
    },
  ],
  conjunction: 'y',
  priceRangeTemplate: `{min} a {max}${NBSP}€`,
  weeksRangeTemplate: '{min} a {max} semanas',
  recapInstructorWords: {
    '1': 'un solo profesor',
    '2-4': '2 a 4 profesores',
    '5-10': '5 a 10 profesores',
    '10+': 'más de 10 profesores',
  },
  recapAgencyWords: { '1': 'un solo centro', '2-3': '2 o 3 centros', '4+': '4 centros o más' },
  recapBookingWords: { phone: 'por teléfono', messages: 'por SMS o WhatsApp', online: 'en línea' },
  recapBookingTemplate: 'reservas {channels}',
  complementPainWords: {
    planning: 'la agenda',
    noshow: 'las cancelaciones',
    hours: 'el seguimiento de horas',
    payments: 'los pagos',
    cpf: 'la financiación',
    progress: 'el libro de aprendizaje',
    exams: 'los exámenes',
    questions: 'las preguntas de los alumnos',
  },
  featuresByPain: {
    planning: 'Una agenda compartida de profesores y coches, sin reservas duplicadas',
    noshow: 'Recordatorios la víspera, la regla de las 48 horas hábiles de tu contrato y una lista de espera',
    hours: 'El contador de horas y de bono de cada alumno, visible desde su lado',
    payments: 'Calendarios de pago y recordatorios automáticos',
    cpf: 'El seguimiento de la formación financiada: cofinanciación, importe a cargo del alumno y plazos',
    progress: 'El libro de aprendizaje del alumno conectado a la agenda, competencia por competencia',
    exams: 'La lista de alumnos listos para el examen y el seguimiento de las plazas',
    questions: 'Un espacio para el alumno: reservas, horas restantes, documentos y pagos',
  },
  checksByPain: {
    planning: '¿La agenda gestiona los coches además de los profesores?',
    noshow: '¿Los recordatorios por SMS están incluidos o se facturan aparte?',
    hours: '¿El alumno ve sus horas restantes y su bono?',
    payments: '¿Se puede pagar a plazos, con recordatorios automáticos?',
    cpf: '¿El programa está conectado a EDOF, la plataforma de las formaciones CPF?',
    exams: '¿El programa ayuda a detectar a los alumnos listos para el examen?',
    questions: '¿Existe una app o un espacio para el alumno?',
  },
  logbookCheck: '¿Incluye el libro de aprendizaje digital, transmitido al Estado francés por la interfaz oficial?',
  dataExportCheck: '¿Puedes exportar tus datos (alumnos, horas, pagos) si cambias de programa?',
  onlineBookingFeature: `La reserva de clases en línea, 24${NBSP}h/24, desde tu propia web`,
  singlePlanningFeature: 'Todas las reservas en una sola agenda, sea cual sea el canal',
  agenciesFeature: 'Una vista por centro y una vista global para la dirección',
  market: {
    eyebrow: 'Presupuesto a prever',
    priceRange: `Gratis a 79${NBSP}€`,
    priceSuffix: 'al mes sin IVA, para un centro',
    priceExamples: [
      { label: 'Ma Gestion Zen', value: `39${NBSP}€/mes` },
      { label: 'Drivup', value: `desde 45${NBSP}€/mes` },
      { label: 'Kréno 2', value: `49${NBSP}€/mes` },
      { label: 'GestAuto-École', value: `79${NBSP}€/mes` },
    ],
    footnote:
      'Drivea y el plan básico de rdv360 son gratuitos: comprueba que gestionan el libro de aprendizaje digital. Klaxo, Rapido, Elgéaweb y AGX funcionan con presupuesto.',
    footnoteLink: { label: 'Ver todos los precios', href: '#programas' },
    adviceTitle: 'Qué comprobar antes de elegir',
    disclaimer: 'Precios públicos sin IVA, consultados a finales de septiembre de 2026.',
    ctaLabel: 'Pedir consejo gratis',
    leadFormTitle: 'Un consejo gratuito para elegir tu programa',
    leadFormIntro: `Te respondo en 24${NBSP}h para hablarlo, por teléfono o videollamada. Tus respuestas al test se adjuntan a tu mensaje.`,
    leadBudget: `Programa del mercado, gratis a 79${NBSP}€ sin IVA al mes`,
  },
  project: {
    eyebrow: 'Orden de precio, a precio cerrado',
    durationLabel: 'Plazo',
    maintenanceLabel: 'Mantenimiento',
    maintenanceValue: `100 a 300${NBSP}€/mes`,
    complementFootnote: 'Se paga una sola vez, además de tu suscripción actual.',
    customFootnote: 'Se paga una sola vez: la herramienta y su código son tuyos.',
    adviceTitle: 'Qué prever primero',
    disclaimer: 'Resultado orientativo. El precio final se fija en el presupuesto.',
    ctaLabel: 'Recibir mi estimación',
    leadFormTitle: 'Recibir mi estimación detallada',
    leadFormIntro: `Te respondo en 24${NBSP}h con primeras ideas y un presupuesto más preciso. Tus respuestas al test se adjuntan a tu mensaje.`,
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'complemento a medida',
    customKind: 'herramienta a medida',
  },
  results: {
    custom: {
      title: 'Una herramienta a medida para tu autoescuela',
      explanation:
        'Con tu tamaño y tus propias reglas, los programas del mercado te obligan a adaptarte a ellos. Una herramienta diseñada para ti sigue tu forma de trabajar y es tuya. El libro de aprendizaje digital, la ANTS y RdvPermis se quedan en un programa homologado, conectado a la herramienta.',
    },
    complement: {
      title: 'Conserva tu programa y añade un complemento a medida',
      explanation:
        'Tu programa hace el trabajo básico, no hace falta cambiarlo. Una pequeña herramienta conectada a él puede resolver lo que aún te quita tiempo{pains}.',
      painsTemplate: ': {list}',
    },
    solo: {
      title: 'Te basta con un programa del mercado',
      explanation: `Para un profesor solo, un programa de menos de 50${NBSP}€ al mes cubre lo esencial: agenda, reserva en línea, seguimiento de horas y libro de aprendizaje digital. Una herramienta a medida no sería rentable.`,
      keepCurrentSentence: ' Si el tuyo te va bien, consérvalo.',
    },
    market: {
      title: 'Por ahora te basta con un programa del mercado',
      explanation: `Con tu tamaño, los programas para autoescuelas del mercado cubren lo esencial: agenda, reserva en línea, seguimiento de horas y libro de aprendizaje digital. Una herramienta a medida te costaría hoy más de lo que te haría ganar.`,
      unfitSentence: ' Si el tuyo no te convence, compara dos o tres con los puntos de abajo antes de cambiar.',
    },
  },
}
