import type { DibodevDrivingSchoolQuizWording } from '~/core/types/DibodevDrivingSchoolSoftwareQuiz'
import { NBSP } from '~/core/constants/typography'

export const DRIVING_SCHOOL_QUIZ_WORDING_FR: DibodevDrivingSchoolQuizWording = {
  numberLocale: 'fr-FR',
  quizName: `Quel logiciel pour votre auto-école${NBSP}?`,
  questions: [
    {
      id: 'instructors',
      title: `Combien de moniteurs travaillent dans votre auto-école${NBSP}?`,
      helpText: 'En vous comptant, si vous donnez aussi des leçons.',
      leadMessageLabel: 'Moniteurs',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'moniteur', icon: null },
        { id: '2-4', label: '2 à 4', unit: 'moniteurs', icon: null },
        { id: '5-10', label: '5 à 10', unit: 'moniteurs', icon: null },
        { id: '10+', label: '+ de 10', unit: 'moniteurs', icon: null },
      ],
    },
    {
      id: 'agencies',
      title: `Sur combien d’agences${NBSP}?`,
      helpText: 'Chaque local où vos élèves s’inscrivent ou retrouvent leur moniteur.',
      leadMessageLabel: 'Agences',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'agence', icon: null },
        { id: '2-3', label: '2 ou 3', unit: 'agences', icon: null },
        { id: '4+', label: '4 et +', unit: 'agences', icon: null },
      ],
    },
    {
      id: 'booking',
      title: `Comment vos élèves réservent-ils leurs leçons aujourd’hui${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Réservations',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'phone', label: 'Par téléphone ou au bureau', unit: '', icon: 'Phone' },
        { id: 'messages', label: 'Par SMS ou WhatsApp', unit: '', icon: 'MessageCircle' },
        { id: 'online', label: 'En ligne, sur un logiciel ou une appli', unit: '', icon: 'Laptop' },
      ],
    },
    {
      id: 'pains',
      title: `Qu’est-ce qui vous prend le plus de temps${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Ce qui prend du temps',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'planning', label: 'Le planning des moniteurs et des voitures', unit: '', icon: null },
        { id: 'noshow', label: 'Les annulations de dernière minute', unit: '', icon: null },
        { id: 'hours', label: 'Le suivi des heures et des forfaits', unit: '', icon: null },
        { id: 'payments', label: 'Les paiements en plusieurs fois et les relances', unit: '', icon: null },
        { id: 'cpf', label: 'Les formations financées (CPF, employeur)', unit: '', icon: null },
        { id: 'progress', label: 'Le livret et la progression des élèves', unit: '', icon: null },
        { id: 'exams', label: 'Les places d’examen et les élèves prêts', unit: '', icon: null },
        { id: 'questions', label: 'Les questions des élèves et des parents', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: `Utilisez-vous déjà un logiciel de gestion${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Logiciel actuel',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'Non, un agenda, du papier ou Excel', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Oui, mais il ne colle pas à notre façon de travailler', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Oui, et il nous convient', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: `Qu’est-ce qui compte le plus pour vous${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Priorité',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Démarrer vite, avec un petit budget', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'Un outil simple que les moniteurs adoptent', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'Un outil qui suit nos forfaits, nos tarifs et nos agences',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        {
          id: 'ownership',
          label: 'Ne plus dépendre d’un abonnement et garder nos données',
          unit: '',
          icon: 'KeyRound',
        },
      ],
    },
  ],
  conjunction: 'et',
  priceRangeTemplate: `{min} à {max}${NBSP}€`,
  weeksRangeTemplate: '{min} à {max} semaines',
  recapInstructorWords: {
    '1': 'un seul moniteur',
    '2-4': '2 à 4 moniteurs',
    '5-10': '5 à 10 moniteurs',
    '10+': 'plus de 10 moniteurs',
  },
  recapAgencyWords: { '1': 'une seule agence', '2-3': '2 ou 3 agences', '4+': '4 agences ou plus' },
  recapBookingWords: { phone: 'par téléphone', messages: 'par SMS ou WhatsApp', online: 'en ligne' },
  recapBookingTemplate: 'réservations {channels}',
  complementPainWords: {
    planning: 'le planning',
    noshow: 'les annulations',
    hours: 'le suivi des heures',
    payments: 'les paiements',
    cpf: 'les financements',
    progress: 'le livret',
    exams: 'les examens',
    questions: 'les questions des élèves',
  },
  featuresByPain: {
    planning: 'Un planning partagé des moniteurs et des voitures, sans double réservation',
    noshow: 'Des rappels la veille, la règle des 48 heures ouvrées de votre contrat et une liste d’attente',
    hours: 'Le compteur d’heures et de forfait de chaque élève, visible de son côté',
    payments: 'Des échéanciers de paiement et des relances automatiques',
    cpf: `Le suivi des formations financées${NBSP}: cofinancement, reste à charge et échéances`,
    progress: 'Le livret de l’élève relié au planning, compétence par compétence',
    exams: 'La liste des élèves prêts pour l’examen et le suivi des places',
    questions: `Un espace élève${NBSP}: réservations, heures restantes, documents et paiements`,
  },
  checksByPain: {
    planning: `Le planning gère-t-il les voitures en plus des moniteurs${NBSP}?`,
    noshow: `Les rappels par SMS sont-ils inclus, ou facturés à part${NBSP}?`,
    hours: `L’élève voit-il ses heures restantes et son forfait${NBSP}?`,
    payments: `Peut-on payer en plusieurs fois et relancer automatiquement${NBSP}?`,
    cpf: `Le logiciel est-il relié à EDOF, la plateforme des formations CPF${NBSP}?`,
    exams: `Le logiciel aide-t-il à repérer les élèves prêts pour l’examen${NBSP}?`,
    questions: `Existe-t-il une appli ou un espace élève${NBSP}?`,
  },
  logbookCheck: `Le livret numérique est-il inclus, et transmis à l’État par l’interface officielle${NBSP}?`,
  dataExportCheck: `Pouvez-vous exporter vos données (élèves, heures, paiements) si vous changez de logiciel${NBSP}?`,
  onlineBookingFeature: `La réservation des leçons en ligne, 24${NBSP}h/24, depuis votre site`,
  singlePlanningFeature: 'Toutes les réservations dans un seul planning, quel que soit le canal',
  agenciesFeature: 'Une vue par agence, et une vue d’ensemble pour la direction',
  market: {
    eyebrow: 'Budget à prévoir',
    priceRange: `Gratuit à 249${NBSP}€`,
    priceSuffix: 'par mois hors taxes, pour une agence',
    priceExamples: [
      { label: 'Ma Gestion Zen', value: `39${NBSP}€/mois` },
      { label: 'Drivup', value: `dès 45${NBSP}€/mois` },
      { label: 'Kréno 2', value: `49${NBSP}€/mois` },
      { label: 'GestAuto-École', value: `79${NBSP}€/mois` },
      { label: 'Klaxo', value: `dès 99${NBSP}€/mois` },
    ],
    footnote: `Drivea et la formule de base de rdv360 sont gratuits${NBSP}: vérifiez alors qu’ils gèrent le livret numérique. Rapido, Elgéaweb et AGX sont sur devis.`,
    footnoteLink: { label: 'Voir tous les prix', href: '#logiciels' },
    adviceTitle: 'À vérifier avant de choisir',
    disclaimer: 'Prix publics hors taxes, relevés fin septembre 2026.',
    ctaLabel: 'Demander un avis gratuit',
    leadFormTitle: 'Un avis gratuit pour choisir votre logiciel',
    leadFormIntro: `Je vous réponds sous 24${NBSP}h pour en parler, au téléphone ou en visio. Vos réponses au test sont jointes à votre message.`,
    leadBudget: `Logiciel du marché, gratuit à 249${NBSP}€ HT par mois`,
  },
  project: {
    eyebrow: 'Ordre de prix, au forfait',
    durationLabel: 'Délai',
    maintenanceLabel: 'Maintenance',
    maintenanceValue: `100 à 300${NBSP}€/mois`,
    complementFootnote: 'Payé une seule fois, en plus de votre abonnement actuel.',
    customFootnote: `Payé une seule fois${NBSP}: l’outil et son code vous appartiennent.`,
    adviceTitle: 'À prévoir en priorité',
    disclaimer: 'Résultat indicatif. Le prix définitif est fixé dans le devis.',
    ctaLabel: 'Recevoir mon estimation',
    leadFormTitle: 'Recevoir mon estimation détaillée',
    leadFormIntro: `Je vous réponds sous 24${NBSP}h avec de premières pistes et un budget plus précis. Vos réponses au test sont jointes à votre message.`,
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'complément sur mesure',
    customKind: 'outil sur mesure',
  },
  results: {
    custom: {
      title: 'Un outil sur mesure pour votre auto-école',
      explanation:
        'À votre taille et avec vos propres règles, les logiciels du marché vous obligent à vous adapter à eux. Un outil conçu pour vous suit votre organisation et vous appartient. Le livret numérique, l’ANTS et RdvPermis restent dans un logiciel conforme, relié à l’outil.',
    },
    complement: {
      title: 'Gardez votre logiciel, ajoutez un complément sur mesure',
      explanation:
        'Votre logiciel fait le travail de base, inutile d’en changer. Un petit outil branché dessus peut régler ce qui vous prend encore du temps{pains}.',
      painsTemplate: `${NBSP}: {list}`,
    },
    solo: {
      title: 'Un logiciel du marché vous suffit',
      explanation: `Pour un moniteur seul, un logiciel à moins de 50${NBSP}€ par mois couvre l’essentiel${NBSP}: planning, réservation en ligne, suivi des heures et livret numérique. Un outil sur mesure ne serait pas rentable.`,
      keepCurrentSentence: ' Si le vôtre vous convient, gardez-le.',
    },
    market: {
      title: 'Un logiciel du marché vous suffit pour l’instant',
      explanation: `À votre taille, les logiciels d’auto-école du marché couvrent l’essentiel${NBSP}: planning, réservation en ligne, suivi des heures et livret numérique. Un outil sur mesure vous coûterait plus qu’il ne vous ferait gagner aujourd’hui.`,
      unfitSentence:
        ' Si le vôtre ne vous convient pas, comparez-en deux ou trois avec les points ci-dessous avant d’en changer.',
    },
  },
}
