import type { DibodevTradeQuizWording } from '~/core/types/DibodevTradeSoftwareQuiz'
import { NBSP } from '~/core/constants/typography'

export const EVENT_RENTAL_QUIZ_WORDING_FR: DibodevTradeQuizWording = {
  numberLocale: 'fr-FR',
  quizName: `Quel logiciel pour votre location de matériel événementiel${NBSP}?`,
  questions: [
    {
      id: 'team',
      title: `Combien de personnes préparent et livrent le matériel${NBSP}?`,
      helpText: 'Vous compris, avec les renforts de la haute saison.',
      leadMessageLabel: 'Équipe',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'personne', icon: null },
        { id: '2-4', label: '2 à 4', unit: 'personnes', icon: null },
        { id: '5-10', label: '5 à 10', unit: 'personnes', icon: null },
        { id: '10+', label: '+ de 10', unit: 'personnes', icon: null },
      ],
    },
    {
      id: 'sites',
      title: `Sur combien de dépôts${NBSP}?`,
      helpText: 'Chaque lieu où votre matériel est stocké entre deux événements.',
      leadMessageLabel: 'Dépôts',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'dépôt', icon: null },
        { id: '2-3', label: '2 ou 3', unit: 'dépôts', icon: null },
        { id: '4+', label: '4 et +', unit: 'dépôts', icon: null },
      ],
    },
    {
      id: 'scope',
      title: `Que louez-vous${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Matériel loué',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'furniture', label: 'Mobilier, vaisselle et linge', unit: '', icon: 'Armchair' },
        { id: 'tents', label: 'Tentes, chapiteaux et barnums', unit: '', icon: 'Tent' },
        { id: 'sound', label: 'Son, lumière et vidéo', unit: '', icon: 'Speaker' },
        { id: 'games', label: 'Jeux et animations', unit: '', icon: 'PartyPopper' },
      ],
    },
    {
      id: 'pains',
      title: `Qu’est-ce qui vous prend le plus de temps${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Ce qui prend du temps',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'availability', label: 'Vérifier les disponibilités avant un devis', unit: '', icon: null },
        { id: 'quotes', label: 'Faire les devis et les contrats', unit: '', icon: null },
        { id: 'prep', label: 'Préparer les sorties et contrôler les retours', unit: '', icon: null },
        { id: 'breakage', label: 'Facturer la casse et les manquants', unit: '', icon: null },
        { id: 'delivery', label: 'Organiser les livraisons et les montages', unit: '', icon: null },
        { id: 'deposits', label: 'Suivre les cautions, acomptes et soldes', unit: '', icon: null },
        { id: 'online', label: 'Répondre aux demandes venues du site', unit: '', icon: null },
        { id: 'documents', label: 'Retrouver les documents du matériel (sécurité, notices)', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: `Utilisez-vous déjà un logiciel de location${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Logiciel actuel',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'Non, un planning Excel ou papier', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Oui, mais il ne colle pas à notre façon de travailler', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Oui, et il nous convient', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: `Qu’est-ce qui compte le plus pour vous${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Priorité',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Démarrer vite, avec un petit budget', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'Un outil simple pour l’équipe au dépôt', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'Un outil qui suit nos kits, nos tarifs et nos dépôts',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        {
          id: 'ownership',
          label: 'Ne plus dépendre d’un abonnement et garder nos données',
          unit: '',
          icon: 'KeyRound',
        },
      ],
    },
  ],
  conjunction: 'et',
  priceRangeTemplate: `{min} à {max}${NBSP}€`,
  weeksRangeTemplate: '{min} à {max} semaines',
  recapTeamWords: {
    '1': 'une seule personne',
    '2-4': '2 à 4 personnes',
    '5-10': '5 à 10 personnes',
    '10+': 'plus de 10 personnes',
  },
  recapSitesWords: { '1': 'un seul dépôt', '2-3': '2 ou 3 dépôts', '4+': '4 dépôts ou plus' },
  recapScopeWords: { furniture: 'mobilier', tents: 'chapiteaux', sound: 'sonorisation', games: 'animations' },
  recapScopeTemplate: 'location de {items}',
  complementPainWords: {
    availability: 'les disponibilités',
    quotes: 'les devis',
    prep: 'les sorties et retours',
    breakage: 'la casse',
    delivery: 'les livraisons',
    deposits: 'les cautions',
    online: 'les demandes en ligne',
    documents: 'les documents',
  },
  features: {
    availability: 'Les disponibilités en temps réel, article par article, avant même d’envoyer le devis',
    quotes: 'Des devis et contrats en quelques clics, avec vos kits et vos tarifs selon la durée',
    prep: 'Des bons de sortie et de retour scannés (QR codes), pour voir tout de suite ce qui manque',
    breakage: 'La casse et les manquants facturés directement depuis le bon de retour',
    delivery: 'Un planning des livraisons et des montages, par camion et par équipe',
    deposits: 'Le suivi des cautions, des acomptes et des soldes, avec paiement en ligne',
    online: 'Un catalogue en ligne relié au stock réel, avec demande de devis',
    documents: 'Les documents de chaque matériel (registre de sécurité, notices) joints aux contrats',
    multiSite: 'Le stock de chaque dépôt, et les transferts d’un dépôt à l’autre',
  },
  checks: {
    primary: `Le logiciel bloque-t-il un article déjà loué sur les mêmes dates, temps de nettoyage compris${NBSP}?`,
    quotes: `Peut-on créer des kits (table, chaises, nappe) et des tarifs selon la durée${NBSP}?`,
    prep: `Y a-t-il une appli pour scanner les sorties et les retours au dépôt${NBSP}?`,
    breakage: `La casse et les manquants se facturent-ils depuis le bon de retour${NBSP}?`,
    delivery: `Le planning gère-t-il les livraisons, les camions et les équipes de montage${NBSP}?`,
    deposits: `Les cautions et acomptes sont-ils suivis, avec paiement en ligne${NBSP}?`,
    online: `Le catalogue en ligne est-il relié au stock réel${NBSP}?`,
    documents: `Peut-on joindre des documents (registre de sécurité, notices) à chaque article${NBSP}?`,
    tents: `Pour les chapiteaux, le registre de sécurité est-il rangé avec chaque structure${NBSP}?`,
    export: `Pouvez-vous exporter vos données (articles, clients, contrats) si vous changez de logiciel${NBSP}?`,
  },
  market: {
    eyebrow: 'Budget à prévoir',
    priceRange: `Gratuit à 150${NBSP}€`,
    priceSuffix: 'par mois, selon les utilisateurs et les modules',
    priceExamples: [
      { label: 'Unipresta', value: 'version gratuite' },
      { label: 'LoKisi', value: `dès 29${NBSP}€/mois` },
      { label: 'Rentman', value: `dès 39${NBSP}€/mois` },
      { label: 'Current RMS', value: `69${NBSP}€/mois` },
    ],
    footnote: `Rentman ajoute des modules par utilisateur, Current RMS 49${NBSP}€ par utilisateur en plus. Booqable coûte 29 à 149${NBSP}$ par mois${NBSP}; Sphinx Manager, Locasyst, Codial et CLE sont sur devis.`,
    footnoteLink: { label: 'Voir tous les prix', href: '#logiciels' },
    adviceTitle: 'À vérifier avant de choisir',
    disclaimer: 'Prix publics relevés le 29 septembre 2026.',
    ctaLabel: 'Demander un avis gratuit',
    leadFormTitle: 'Un avis gratuit pour choisir votre logiciel',
    leadFormIntro: `Je vous réponds sous 24${NBSP}h pour en parler, au téléphone ou en visio. Vos réponses au test sont jointes à votre message.`,
    leadBudget: `Logiciel du marché, gratuit à 150${NBSP}€ par mois`,
  },
  project: {
    eyebrow: 'Ordre de prix, au forfait',
    durationLabel: 'Délai',
    maintenanceLabel: 'Maintenance',
    maintenanceValue: `100 à 300${NBSP}€/mois`,
    complementFootnote: 'Payé une seule fois, en plus de votre abonnement actuel.',
    customFootnote: `Payé une seule fois${NBSP}: l’outil et son code vous appartiennent.`,
    adviceTitle: 'À prévoir en priorité',
    disclaimer: 'Résultat indicatif. Le prix définitif est fixé dans le devis.',
    ctaLabel: 'Recevoir mon estimation',
    leadFormTitle: 'Recevoir mon estimation détaillée',
    leadFormIntro: `Je vous réponds sous 24${NBSP}h avec de premières pistes et un budget plus précis. Vos réponses au test sont jointes à votre message.`,
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'complément sur mesure',
    customKind: 'outil sur mesure',
  },
  results: {
    custom: {
      title: 'Un outil sur mesure pour votre parc de location',
      explanation:
        'À votre taille et avec vos propres règles (kits, tarifs, dépôts), les logiciels du marché vous obligent à vous adapter à eux. Un outil conçu pour vous suit votre organisation et vous appartient. Votre comptabilité reste dans votre logiciel comptable, relié à l’outil.',
    },
    complement: {
      title: 'Gardez votre logiciel, ajoutez un complément sur mesure',
      explanation:
        'Votre logiciel fait le travail de base, inutile d’en changer. Un petit outil branché dessus peut régler ce qui vous prend encore du temps{pains}.',
      painsTemplate: `${NBSP}: {list}`,
    },
    solo: {
      title: 'Un logiciel du marché vous suffit',
      explanation: `Seul pour préparer et livrer, un logiciel à moins de 40${NBSP}€ par mois couvre l’essentiel${NBSP}: disponibilités, devis, sorties et retours. Un outil sur mesure ne serait pas rentable.`,
      keepCurrentSentence: ' Si le vôtre vous convient, gardez-le.',
    },
    market: {
      title: 'Un logiciel du marché vous suffit pour l’instant',
      explanation: `À votre taille, les logiciels de location du marché couvrent l’essentiel${NBSP}: disponibilités, devis, contrats, sorties et retours. Un outil sur mesure vous coûterait plus qu’il ne vous ferait gagner aujourd’hui.`,
      unfitSentence:
        ' Si le vôtre ne vous convient pas, comparez-en deux ou trois avec les points ci-dessous avant d’en changer.',
    },
  },
}
