import type { DibodevTradeQuizWording } from '~/core/types/DibodevTradeSoftwareQuiz'
import { NBSP } from '~/core/constants/typography'

export const EVENT_RENTAL_QUIZ_WORDING_ES: DibodevTradeQuizWording = {
  numberLocale: 'es-ES',
  quizName: '¿Qué software para tu empresa de alquiler de material para eventos?',
  questions: [
    {
      id: 'team',
      title: '¿Cuántas personas preparan y entregan el material?',
      helpText: 'Contándote a ti, con los refuerzos de temporada alta.',
      leadMessageLabel: 'Equipo',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'persona', icon: null },
        { id: '2-4', label: '2 a 4', unit: 'personas', icon: null },
        { id: '5-10', label: '5 a 10', unit: 'personas', icon: null },
        { id: '10+', label: '+ de 10', unit: 'personas', icon: null },
      ],
    },
    {
      id: 'sites',
      title: '¿En cuántos almacenes?',
      helpText: 'Cada lugar donde guardas el material entre dos eventos.',
      leadMessageLabel: 'Almacenes',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'almacén', icon: null },
        { id: '2-3', label: '2 o 3', unit: 'almacenes', icon: null },
        { id: '4+', label: '4 o más', unit: 'almacenes', icon: null },
      ],
    },
    {
      id: 'scope',
      title: '¿Qué alquilas?',
      helpText: '',
      leadMessageLabel: 'Material alquilado',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'furniture', label: 'Mobiliario, vajilla y mantelería', unit: '', icon: 'Armchair' },
        { id: 'tents', label: 'Carpas, jaimas y cenadores', unit: '', icon: 'Tent' },
        { id: 'sound', label: 'Sonido, iluminación y vídeo', unit: '', icon: 'Speaker' },
        { id: 'games', label: 'Juegos y animación', unit: '', icon: 'PartyPopper' },
      ],
    },
    {
      id: 'pains',
      title: '¿Qué es lo que más tiempo te quita?',
      helpText: '',
      leadMessageLabel: 'Lo que quita tiempo',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'availability', label: 'Comprobar la disponibilidad antes de un presupuesto', unit: '', icon: null },
        { id: 'quotes', label: 'Hacer los presupuestos y los contratos', unit: '', icon: null },
        { id: 'prep', label: 'Preparar las salidas y revisar las devoluciones', unit: '', icon: null },
        { id: 'breakage', label: 'Facturar las roturas y lo que falta', unit: '', icon: null },
        { id: 'delivery', label: 'Organizar las entregas y los montajes', unit: '', icon: null },
        { id: 'deposits', label: 'Seguir las fianzas, anticipos y saldos', unit: '', icon: null },
        { id: 'online', label: 'Responder a las solicitudes de la web', unit: '', icon: null },
        { id: 'documents', label: 'Encontrar los documentos del material (seguridad, manuales)', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: '¿Ya usas un software de alquiler?',
      helpText: '',
      leadMessageLabel: 'Software actual',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'No, una agenda en Excel o en papel', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Sí, pero no se adapta a nuestra forma de trabajar', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Sí, y nos va bien', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: '¿Qué es lo más importante para ti?',
      helpText: '',
      leadMessageLabel: 'Prioridad',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Empezar rápido, con poco presupuesto', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'Una herramienta sencilla para el equipo del almacén', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'Una herramienta que siga nuestros packs, tarifas y almacenes',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        {
          id: 'ownership',
          label: 'Dejar de depender de una suscripción y conservar nuestros datos',
          unit: '',
          icon: 'KeyRound',
        },
      ],
    },
  ],
  conjunction: 'y',
  priceRangeTemplate: `{min} a {max}${NBSP}€`,
  weeksRangeTemplate: '{min} a {max} semanas',
  recapTeamWords: {
    '1': 'una sola persona',
    '2-4': '2 a 4 personas',
    '5-10': '5 a 10 personas',
    '10+': 'más de 10 personas',
  },
  recapSitesWords: { '1': 'un solo almacén', '2-3': '2 o 3 almacenes', '4+': '4 almacenes o más' },
  recapScopeWords: { furniture: 'mobiliario', tents: 'carpas', sound: 'sonido', games: 'animación' },
  recapScopeTemplate: 'alquiler de {items}',
  complementPainWords: {
    availability: 'la disponibilidad',
    quotes: 'los presupuestos',
    prep: 'las salidas y devoluciones',
    breakage: 'las roturas',
    delivery: 'las entregas',
    deposits: 'las fianzas',
    online: 'las solicitudes en línea',
    documents: 'los documentos',
  },
  features: {
    availability: 'La disponibilidad en tiempo real, artículo por artículo, antes incluso de enviar el presupuesto',
    quotes: 'Presupuestos y contratos en pocos clics, con tus packs y tus tarifas según la duración',
    prep: 'Albaranes de salida y de devolución escaneados (códigos QR), para ver al instante lo que falta',
    breakage: 'Las roturas y lo que falta facturados directamente desde el albarán de devolución',
    delivery: 'Una agenda de entregas y montajes, por furgoneta y por equipo',
    deposits: 'El seguimiento de fianzas, anticipos y saldos, con pago en línea',
    online: 'Un catálogo en línea conectado al stock real, con solicitud de presupuesto',
    documents: 'Los documentos de cada material (registro de seguridad, manuales) adjuntos a los contratos',
    multiSite: 'El stock de cada almacén y los traslados de un almacén a otro',
  },
  checks: {
    primary: '¿Bloquea el software un artículo ya alquilado en las mismas fechas, incluido el tiempo de limpieza?',
    quotes: '¿Se pueden crear packs (mesa, sillas, mantel) y tarifas según la duración?',
    prep: '¿Hay una app para escanear las salidas y las devoluciones en el almacén?',
    breakage: '¿Se facturan las roturas y lo que falta desde el albarán de devolución?',
    delivery: '¿La agenda gestiona las entregas, las furgonetas y los equipos de montaje?',
    deposits: '¿Se siguen las fianzas y los anticipos, con pago en línea?',
    online: '¿El catálogo en línea está conectado al stock real?',
    documents: '¿Se pueden adjuntar documentos (registro de seguridad, manuales) a cada artículo?',
    tents: 'Para las carpas, ¿el registro de seguridad se guarda con cada estructura?',
    export: '¿Puedes exportar tus datos (artículos, clientes, contratos) si cambias de software?',
  },
  market: {
    eyebrow: 'Presupuesto a prever',
    priceRange: `Gratis a 150${NBSP}€`,
    priceSuffix: 'al mes, según los usuarios y los módulos',
    priceExamples: [
      { label: 'Unipresta', value: 'versión gratuita' },
      { label: 'LoKisi', value: `desde 29${NBSP}€/mes` },
      { label: 'Rentman', value: `desde 39${NBSP}€/mes` },
      { label: 'Current RMS', value: `69${NBSP}€/mes` },
    ],
    footnote: `Rentman añade módulos por usuario, Current RMS 49${NBSP}€ por usuario adicional. Booqable cuesta de 29 a 149${NBSP}$ al mes; Sphinx Manager, Locasyst, Codial y CLE funcionan con presupuesto.`,
    footnoteLink: { label: 'Ver todos los precios', href: '#programas' },
    adviceTitle: 'Qué comprobar antes de elegir',
    disclaimer: 'Precios públicos consultados el 29 de septiembre de 2026.',
    ctaLabel: 'Pedir consejo gratis',
    leadFormTitle: 'Un consejo gratuito para elegir tu software',
    leadFormIntro: `Te respondo en 24${NBSP}h para hablarlo, por teléfono o videollamada. Tus respuestas al test se adjuntan a tu mensaje.`,
    leadBudget: `Software del mercado, gratis a 150${NBSP}€ al mes`,
  },
  project: {
    eyebrow: 'Orden de precio, a precio cerrado',
    durationLabel: 'Plazo',
    maintenanceLabel: 'Mantenimiento',
    maintenanceValue: `100 a 300${NBSP}€/mes`,
    complementFootnote: 'Se paga una sola vez, además de tu suscripción actual.',
    customFootnote: 'Se paga una sola vez: la herramienta y su código son tuyos.',
    adviceTitle: 'Qué prever primero',
    disclaimer: 'Resultado orientativo. El precio final se fija en el presupuesto.',
    ctaLabel: 'Recibir mi estimación',
    leadFormTitle: 'Recibir mi estimación detallada',
    leadFormIntro: `Te respondo en 24${NBSP}h con primeras ideas y un presupuesto más preciso. Tus respuestas al test se adjuntan a tu mensaje.`,
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'complemento a medida',
    customKind: 'herramienta a medida',
  },
  results: {
    custom: {
      title: 'Una herramienta a medida para tu empresa de alquiler',
      explanation:
        'Con tu tamaño y tus propias reglas (packs, tarifas, almacenes), los programas del mercado te obligan a adaptarte a ellos. Una herramienta diseñada para ti sigue tu forma de trabajar y es tuya. Tu contabilidad sigue en tu programa contable, conectado a la herramienta.',
    },
    complement: {
      title: 'Conserva tu software y añade un complemento a medida',
      explanation:
        'Tu software hace el trabajo básico, no hace falta cambiarlo. Una pequeña herramienta conectada a él puede resolver lo que aún te quita tiempo{pains}.',
      painsTemplate: ': {list}',
    },
    solo: {
      title: 'Te basta con un software del mercado',
      explanation: `Si preparas y entregas tú solo, un software de menos de 40${NBSP}€ al mes cubre lo esencial: disponibilidad, presupuestos, salidas y devoluciones. Una herramienta a medida no sería rentable.`,
      keepCurrentSentence: ' Si el tuyo te va bien, consérvalo.',
    },
    market: {
      title: 'Por ahora te basta con un software del mercado',
      explanation:
        'Con tu tamaño, los programas de alquiler del mercado cubren lo esencial: disponibilidad, presupuestos, contratos, salidas y devoluciones. Una herramienta a medida te costaría hoy más de lo que te haría ganar.',
      unfitSentence: ' Si el tuyo no te convence, compara dos o tres con los puntos de abajo antes de cambiar.',
    },
  },
}
