import type { DibodevTradeQuizWording } from '~/core/types/DibodevTradeSoftwareQuiz'

export const EVENT_RENTAL_QUIZ_WORDING_EN: DibodevTradeQuizWording = {
  numberLocale: 'en-GB',
  quizName: 'Which software for your event equipment rental business?',
  questions: [
    {
      id: 'team',
      title: 'How many people prepare and deliver the equipment?',
      helpText: 'Including you, and the extra hands of the busy season.',
      leadMessageLabel: 'Team',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'person', icon: null },
        { id: '2-4', label: '2 to 4', unit: 'people', icon: null },
        { id: '5-10', label: '5 to 10', unit: 'people', icon: null },
        { id: '10+', label: '10+', unit: 'people', icon: null },
      ],
    },
    {
      id: 'sites',
      title: 'How many warehouses?',
      helpText: 'Each place where your equipment is stored between two events.',
      leadMessageLabel: 'Warehouses',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'warehouse', icon: null },
        { id: '2-3', label: '2 or 3', unit: 'warehouses', icon: null },
        { id: '4+', label: '4+', unit: 'warehouses', icon: null },
      ],
    },
    {
      id: 'scope',
      title: 'What do you rent out?',
      helpText: '',
      leadMessageLabel: 'Equipment rented',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'furniture', label: 'Furniture, tableware and linen', unit: '', icon: 'Armchair' },
        { id: 'tents', label: 'Tents, marquees and gazebos', unit: '', icon: 'Tent' },
        { id: 'sound', label: 'Sound, lighting and video', unit: '', icon: 'Speaker' },
        { id: 'games', label: 'Games and entertainment', unit: '', icon: 'PartyPopper' },
      ],
    },
    {
      id: 'pains',
      title: 'What takes up most of your time?',
      helpText: '',
      leadMessageLabel: 'Time-consuming tasks',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'availability', label: 'Checking availability before a quote', unit: '', icon: null },
        { id: 'quotes', label: 'Writing quotes and contracts', unit: '', icon: null },
        { id: 'prep', label: 'Preparing orders and checking returns', unit: '', icon: null },
        { id: 'breakage', label: 'Billing breakages and missing items', unit: '', icon: null },
        { id: 'delivery', label: 'Planning deliveries and set-ups', unit: '', icon: null },
        { id: 'deposits', label: 'Following deposits, down payments and balances', unit: '', icon: null },
        { id: 'online', label: 'Answering requests from the website', unit: '', icon: null },
        { id: 'documents', label: 'Finding equipment documents (safety, manuals)', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: 'Do you already use rental software?',
      helpText: '',
      leadMessageLabel: 'Current software',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'No: an Excel or paper schedule', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Yes, but it does not fit the way we work', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Yes, and it suits us', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: 'What matters most to you?',
      helpText: '',
      leadMessageLabel: 'Priority',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Getting started quickly, on a small budget', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'A simple tool for the warehouse team', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'A tool that follows our kits, prices and warehouses',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        { id: 'ownership', label: 'No more subscription, and keeping our data', unit: '', icon: 'KeyRound' },
      ],
    },
  ],
  conjunction: 'and',
  priceRangeTemplate: '€{min} to €{max}',
  weeksRangeTemplate: '{min} to {max} weeks',
  recapTeamWords: { '1': 'one person', '2-4': '2 to 4 people', '5-10': '5 to 10 people', '10+': 'more than 10 people' },
  recapSitesWords: { '1': 'one warehouse', '2-3': '2 or 3 warehouses', '4+': '4 warehouses or more' },
  recapScopeWords: { furniture: 'furniture', tents: 'marquees', sound: 'sound equipment', games: 'entertainment' },
  recapScopeTemplate: 'renting out {items}',
  complementPainWords: {
    availability: 'availability',
    quotes: 'quotes',
    prep: 'orders and returns',
    breakage: 'breakages',
    delivery: 'deliveries',
    deposits: 'deposits',
    online: 'online requests',
    documents: 'documents',
  },
  features: {
    availability: 'Real-time availability, item by item, before you even send the quote',
    quotes: 'Quotes and contracts in a few clicks, with your kits and prices by rental length',
    prep: 'Scanned delivery and return notes (QR codes), to see at once what is missing',
    breakage: 'Breakages and missing items billed straight from the return note',
    delivery: 'A schedule of deliveries and set-ups, by van and by crew',
    deposits: 'Tracking of deposits, down payments and balances, with online payment',
    online: 'An online catalogue linked to the real stock, with quote requests',
    documents: 'Each item’s documents (safety register, manuals) attached to the contracts',
    multiSite: 'The stock of each warehouse, and transfers from one warehouse to another',
  },
  checks: {
    primary: 'Does the software block an item already rented on the same dates, cleaning time included?',
    quotes: 'Can you create kits (table, chairs, tablecloth) and prices by rental length?',
    prep: 'Is there an app to scan orders and returns at the warehouse?',
    breakage: 'Can breakages and missing items be billed from the return note?',
    delivery: 'Does the schedule handle deliveries, vans and set-up crews?',
    deposits: 'Are deposits and down payments tracked, with online payment?',
    online: 'Is the online catalogue linked to the real stock?',
    documents: 'Can you attach documents (safety register, manuals) to each item?',
    tents: 'For marquees, is the safety register stored with each structure?',
    export: 'Can you export your data (items, customers, contracts) if you change software?',
  },
  market: {
    eyebrow: 'Budget to plan',
    priceRange: 'Free to €150',
    priceSuffix: 'per month, depending on users and modules',
    priceExamples: [
      { label: 'Unipresta', value: 'free version' },
      { label: 'LoKisi', value: 'from €29/month' },
      { label: 'Rentman', value: 'from €39/month' },
      { label: 'Current RMS', value: '€69/month' },
    ],
    footnote:
      'Rentman adds modules per user, Current RMS €49 per extra user. Booqable costs $29 to $149 per month; Sphinx Manager, Locasyst, Codial and CLE are on quote.',
    footnoteLink: { label: 'See all prices', href: '#software' },
    adviceTitle: 'What to check before choosing',
    disclaimer: 'Public prices checked on 29 September 2026.',
    ctaLabel: 'Get free advice',
    leadFormTitle: 'Free advice to choose your software',
    leadFormIntro:
      'I reply within 24 hours to talk it through, by phone or video call. Your test answers are attached to your message.',
    leadBudget: 'Off-the-shelf software, free to €150 per month',
  },
  project: {
    eyebrow: 'Price range, fixed price',
    durationLabel: 'Timeline',
    maintenanceLabel: 'Maintenance',
    maintenanceValue: '€100 to €300/month',
    complementFootnote: 'Paid once, on top of your current subscription.',
    customFootnote: 'Paid once: the tool and its code belong to you.',
    adviceTitle: 'What to plan first',
    disclaimer: 'Indicative result. The final price is set in the quote.',
    ctaLabel: 'Get my estimate',
    leadFormTitle: 'Get my detailed estimate',
    leadFormIntro:
      'I reply within 24 hours with first ideas and a more precise budget. Your test answers are attached to your message.',
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'custom extension',
    customKind: 'custom tool',
  },
  results: {
    custom: {
      title: 'A custom tool for your rental business',
      explanation:
        'At your size and with your own rules (kits, prices, warehouses), off-the-shelf software makes you adapt to it. A tool designed for you follows the way you work and belongs to you. Your accounts stay in your accounting software, connected to the tool.',
    },
    complement: {
      title: 'Keep your software and add a custom extension',
      explanation:
        'Your software does the basics, there is no need to change it. A small tool plugged into it can handle what still takes up your time{pains}.',
      painsTemplate: ': {list}',
    },
    solo: {
      title: 'Off-the-shelf software is enough for you',
      explanation:
        'Preparing and delivering on your own, software under €40 a month covers the essentials: availability, quotes, orders and returns. A custom tool would not pay off.',
      keepCurrentSentence: ' If yours suits you, keep it.',
    },
    market: {
      title: 'Off-the-shelf software is enough for now',
      explanation:
        'At your size, the rental software on the market covers the essentials: availability, quotes, contracts, orders and returns. A custom tool would cost you more than it would save you today.',
      unfitSentence: ' If yours does not suit you, compare two or three with the points below before switching.',
    },
  },
}
