import type { DibodevTradeQuizWording } from '~/core/types/DibodevTradeSoftwareQuiz'
import { NBSP } from '~/core/constants/typography'

export const AUTO_REPAIR_QUIZ_WORDING_FR: DibodevTradeQuizWording = {
  numberLocale: 'fr-FR',
  quizName: `Quel logiciel pour votre garage${NBSP}?`,
  questions: [
    {
      id: 'team',
      title: `Combien de personnes travaillent au garage${NBSP}?`,
      helpText: 'Mécaniciens, accueil et vous compris.',
      leadMessageLabel: 'Équipe',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'personne', icon: null },
        { id: '2-4', label: '2 à 4', unit: 'personnes', icon: null },
        { id: '5-10', label: '5 à 10', unit: 'personnes', icon: null },
        { id: '10+', label: '+ de 10', unit: 'personnes', icon: null },
      ],
    },
    {
      id: 'sites',
      title: `Sur combien d’ateliers${NBSP}?`,
      helpText: 'Chaque adresse où vous recevez des véhicules.',
      leadMessageLabel: 'Ateliers',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'atelier', icon: null },
        { id: '2-3', label: '2 ou 3', unit: 'ateliers', icon: null },
        { id: '4+', label: '4 et +', unit: 'ateliers', icon: null },
      ],
    },
    {
      id: 'scope',
      title: `Que faites-vous${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Activités',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'mechanics', label: 'Mécanique et entretien', unit: '', icon: 'Wrench' },
        { id: 'body', label: 'Carrosserie et peinture', unit: '', icon: 'SprayCan' },
        { id: 'tyres', label: 'Pneus et géométrie', unit: '', icon: 'Disc' },
        { id: 'used', label: 'Vente de véhicules d’occasion', unit: '', icon: 'Car' },
      ],
    },
    {
      id: 'pains',
      title: `Qu’est-ce qui vous prend le plus de temps${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Ce qui prend du temps',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'booking', label: 'Prendre les rendez-vous au téléphone', unit: '', icon: null },
        { id: 'quotes', label: 'Faire les devis (pièces et main-d’œuvre)', unit: '', icon: null },
        { id: 'orders', label: 'Remplir les ordres de réparation', unit: '', icon: null },
        { id: 'parts', label: 'Commander les pièces et suivre le stock', unit: '', icon: null },
        { id: 'invoices', label: 'Faire les factures et relancer les impayés', unit: '', icon: null },
        { id: 'history', label: 'Retrouver l’historique d’un véhicule', unit: '', icon: null },
        { id: 'reuse', label: 'Proposer des pièces de réemploi', unit: '', icon: null },
        { id: 'used', label: 'Suivre les véhicules d’occasion à vendre', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: `Utilisez-vous déjà un logiciel de garage${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Logiciel actuel',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'Non, du papier, Excel ou Word', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Oui, mais il ne colle pas à notre façon de travailler', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Oui, et il nous convient', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: `Qu’est-ce qui compte le plus pour vous${NBSP}?`,
      helpText: '',
      leadMessageLabel: 'Priorité',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Démarrer vite, avec un petit budget', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'Un outil simple pour l’atelier', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'Un outil qui suit nos forfaits, nos taux horaires et nos ateliers',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        {
          id: 'ownership',
          label: 'Ne plus dépendre d’un abonnement et garder nos données',
          unit: '',
          icon: 'KeyRound',
        },
      ],
    },
  ],
  conjunction: 'et',
  priceRangeTemplate: `{min} à {max}${NBSP}€`,
  weeksRangeTemplate: '{min} à {max} semaines',
  recapTeamWords: {
    '1': 'une seule personne',
    '2-4': '2 à 4 personnes',
    '5-10': '5 à 10 personnes',
    '10+': 'plus de 10 personnes',
  },
  recapSitesWords: { '1': 'un seul atelier', '2-3': '2 ou 3 ateliers', '4+': '4 ateliers ou plus' },
  recapScopeWords: { mechanics: 'mécanique', body: 'carrosserie', tyres: 'pneus', used: 'occasion' },
  recapScopeTemplate: '{items}',
  complementPainWords: {
    booking: 'les rendez-vous',
    quotes: 'les devis',
    orders: 'les ordres de réparation',
    parts: 'les pièces',
    invoices: 'les factures',
    history: 'l’historique des véhicules',
    reuse: 'les pièces de réemploi',
    used: 'les véhicules d’occasion',
  },
  features: {
    booking: 'La prise de rendez-vous en ligne, sur votre site, selon la place réelle à l’atelier',
    quotes: 'Des devis en quelques clics, avec vos forfaits, vos taux horaires et vos pièces',
    orders: 'Le devis accepté transformé en ordre de réparation signé, puis en facture, sans ressaisie',
    parts: 'Les pièces commandées pour chaque intervention, et le stock mis à jour à la pose',
    invoices: 'Des factures conformes envoyées tout de suite, avec relance automatique des impayés',
    history: 'L’historique de chaque véhicule (interventions, kilométrage, pièces) retrouvé par sa plaque',
    reuse: 'Une pièce de réemploi proposée sur le devis dès que la réparation y a droit',
    used: 'Le suivi des véhicules d’occasion, de la reprise à la vente, avec les frais engagés',
    photos: 'Les photos du véhicule à l’arrivée, jointes à l’ordre de réparation',
    multiSite: 'Le planning et le stock de chaque atelier, et les transferts de pièces d’un atelier à l’autre',
  },
  checks: {
    primary: `Le devis devient-il ordre de réparation puis facture, sans rien ressaisir${NBSP}?`,
    booking: `Vos clients peuvent-ils prendre rendez-vous en ligne, sur votre site${NBSP}?`,
    quotes: `Peut-on enregistrer vos forfaits et vos taux horaires TTC${NBSP}?`,
    orders: `L’ordre de réparation se signe-t-il sur tablette, avec le kilométrage${NBSP}?`,
    parts: `Le stock se met-il à jour quand une pièce est posée${NBSP}?`,
    invoices: `Les factures sont-elles prêtes pour la facture électronique (Factur-X)${NBSP}?`,
    history: `Retrouve-t-on l’historique d’un véhicule par sa plaque${NBSP}?`,
    reuse: `Le devis permet-il de proposer une pièce de réemploi${NBSP}?`,
    used: `Peut-on suivre les véhicules d’occasion et leurs frais de remise en état${NBSP}?`,
    photos: `Peut-on joindre des photos du véhicule à l’ordre de réparation${NBSP}?`,
    export: `Pouvez-vous exporter vos données (clients, véhicules, factures) si vous changez de logiciel${NBSP}?`,
  },
  market: {
    eyebrow: 'Budget à prévoir',
    priceRange: `19 à 90${NBSP}€`,
    priceSuffix: 'par mois, selon les modules et les utilisateurs',
    priceExamples: [
      { label: 'Gest’Garage', value: `19${NBSP}€/mois` },
      { label: 'TDV', value: `19,90 à 24,90${NBSP}€ TTC/mois` },
      { label: 'AutoProGestion', value: `29 ou 59${NBSP}€/mois` },
      { label: 'Kwixéo', value: `22 à 89${NBSP}€ HT/mois` },
    ],
    footnote: `Kwixéo coûte 18,33 à 74,17${NBSP}€ HT par mois payé à l’année. EBP MéCa et GAD Garage sont sur devis.`,
    footnoteLink: { label: 'Voir tous les prix', href: '#logiciels' },
    adviceTitle: 'À vérifier avant de choisir',
    disclaimer: 'Prix publics relevés le 29 septembre 2026.',
    ctaLabel: 'Demander un avis gratuit',
    leadFormTitle: 'Un avis gratuit pour choisir votre logiciel',
    leadFormIntro: `Je vous réponds sous 24${NBSP}h pour en parler, au téléphone ou en visio. Vos réponses au test sont jointes à votre message.`,
    leadBudget: `Logiciel du marché, 19 à 90${NBSP}€ par mois`,
  },
  project: {
    eyebrow: 'Ordre de prix, au forfait',
    durationLabel: 'Délai',
    maintenanceLabel: 'Maintenance',
    maintenanceValue: `100 à 300${NBSP}€/mois`,
    complementFootnote: 'Payé une seule fois, en plus de votre abonnement actuel.',
    customFootnote: `Payé une seule fois${NBSP}: l’outil et son code vous appartiennent.`,
    adviceTitle: 'À prévoir en priorité',
    disclaimer: 'Résultat indicatif. Le prix définitif est fixé dans le devis.',
    ctaLabel: 'Recevoir mon estimation',
    leadFormTitle: 'Recevoir mon estimation détaillée',
    leadFormIntro: `Je vous réponds sous 24${NBSP}h avec de premières pistes et un budget plus précis. Vos réponses au test sont jointes à votre message.`,
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'complément sur mesure',
    customKind: 'outil sur mesure',
  },
  results: {
    custom: {
      title: 'Un outil sur mesure pour votre garage',
      explanation:
        'À votre taille et avec vos propres règles (forfaits, taux horaires, ateliers), les logiciels du marché vous obligent à vous adapter à eux. Un outil conçu pour vous suit votre organisation et vous appartient. Votre comptabilité reste dans votre logiciel comptable, relié à l’outil.',
    },
    complement: {
      title: 'Gardez votre logiciel, ajoutez un complément sur mesure',
      explanation:
        'Votre logiciel fait le travail de base, inutile d’en changer. Un petit outil branché dessus peut régler ce qui vous prend encore du temps{pains}.',
      painsTemplate: `${NBSP}: {list}`,
    },
    solo: {
      title: 'Un logiciel du marché vous suffit',
      explanation: `Seul au garage, un logiciel à moins de 30${NBSP}€ par mois couvre l’essentiel${NBSP}: devis, ordres de réparation, factures et historique des véhicules. Un outil sur mesure ne serait pas rentable.`,
      keepCurrentSentence: ' Si le vôtre vous convient, gardez-le.',
    },
    market: {
      title: 'Un logiciel du marché vous suffit pour l’instant',
      explanation: `À votre taille, les logiciels de garage du marché couvrent l’essentiel${NBSP}: rendez-vous, devis, ordres de réparation, stock et factures. Un outil sur mesure vous coûterait plus qu’il ne vous ferait gagner aujourd’hui.`,
      unfitSentence:
        ' Si le vôtre ne vous convient pas, comparez-en deux ou trois avec les points ci-dessous avant d’en changer.',
    },
  },
}
