import type { DibodevTradeQuizWording } from '~/core/types/DibodevTradeSoftwareQuiz'

export const AUTO_REPAIR_QUIZ_WORDING_EN: DibodevTradeQuizWording = {
  numberLocale: 'en-GB',
  quizName: 'Which software for your garage?',
  questions: [
    {
      id: 'team',
      title: 'How many people work at the garage?',
      helpText: 'Mechanics, front desk and you included.',
      leadMessageLabel: 'Team',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'person', icon: null },
        { id: '2-4', label: '2 to 4', unit: 'people', icon: null },
        { id: '5-10', label: '5 to 10', unit: 'people', icon: null },
        { id: '10+', label: '10+', unit: 'people', icon: null },
      ],
    },
    {
      id: 'sites',
      title: 'How many workshops?',
      helpText: 'Each address where you take in vehicles.',
      leadMessageLabel: 'Workshops',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'workshop', icon: null },
        { id: '2-3', label: '2 or 3', unit: 'workshops', icon: null },
        { id: '4+', label: '4+', unit: 'workshops', icon: null },
      ],
    },
    {
      id: 'scope',
      title: 'What do you do?',
      helpText: '',
      leadMessageLabel: 'Activities',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'mechanics', label: 'Mechanics and servicing', unit: '', icon: 'Wrench' },
        { id: 'body', label: 'Bodywork and paint', unit: '', icon: 'SprayCan' },
        { id: 'tyres', label: 'Tyres and wheel alignment', unit: '', icon: 'Disc' },
        { id: 'used', label: 'Used vehicle sales', unit: '', icon: 'Car' },
      ],
    },
    {
      id: 'pains',
      title: 'What takes up most of your time?',
      helpText: '',
      leadMessageLabel: 'Time-consuming tasks',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'booking', label: 'Taking bookings over the phone', unit: '', icon: null },
        { id: 'quotes', label: 'Writing quotes (parts and labour)', unit: '', icon: null },
        { id: 'orders', label: 'Filling in repair orders', unit: '', icon: null },
        { id: 'parts', label: 'Ordering parts and tracking stock', unit: '', icon: null },
        { id: 'invoices', label: 'Writing invoices and chasing unpaid ones', unit: '', icon: null },
        { id: 'history', label: 'Finding a vehicle’s history', unit: '', icon: null },
        { id: 'reuse', label: 'Offering reused parts', unit: '', icon: null },
        { id: 'used', label: 'Tracking used vehicles for sale', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: 'Do you already use garage software?',
      helpText: '',
      leadMessageLabel: 'Current software',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'No: paper, Excel or Word', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Yes, but it does not fit the way we work', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Yes, and it suits us', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: 'What matters most to you?',
      helpText: '',
      leadMessageLabel: 'Priority',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Getting started quickly, on a small budget', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'A simple tool for the workshop', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'A tool that follows our service packages, hourly rates and workshops',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        { id: 'ownership', label: 'No more subscription, and keeping our data', unit: '', icon: 'KeyRound' },
      ],
    },
  ],
  conjunction: 'and',
  priceRangeTemplate: '€{min} to €{max}',
  weeksRangeTemplate: '{min} to {max} weeks',
  recapTeamWords: { '1': 'one person', '2-4': '2 to 4 people', '5-10': '5 to 10 people', '10+': 'more than 10 people' },
  recapSitesWords: { '1': 'one workshop', '2-3': '2 or 3 workshops', '4+': '4 workshops or more' },
  recapScopeWords: { mechanics: 'mechanics', body: 'bodywork', tyres: 'tyres', used: 'used vehicles' },
  recapScopeTemplate: '{items}',
  complementPainWords: {
    booking: 'bookings',
    quotes: 'quotes',
    orders: 'repair orders',
    parts: 'parts',
    invoices: 'invoices',
    history: 'vehicle history',
    reuse: 'reused parts',
    used: 'used vehicles',
  },
  features: {
    booking: 'Online booking on your website, based on the real space in the workshop',
    quotes: 'Quotes in a few clicks, with your service packages, hourly rates and parts',
    orders: 'The accepted quote turned into a signed repair order, then an invoice, with no retyping',
    parts: 'Parts ordered for each job, and stock updated when they are fitted',
    invoices: 'Compliant invoices sent straight away, with automatic reminders for unpaid ones',
    history: 'Each vehicle’s history (jobs, mileage, parts) found from its number plate',
    reuse: 'A reused part offered on the quote whenever the repair allows it',
    used: 'Used vehicles tracked from trade-in to sale, with the costs spent on them',
    photos: 'Photos of the vehicle on arrival, attached to the repair order',
    multiSite: 'The schedule and stock of each workshop, and parts transfers between workshops',
  },
  checks: {
    primary: 'Does the quote become a repair order, then an invoice, with nothing to retype?',
    booking: 'Can your customers book online, on your website?',
    quotes: 'Can you save your service packages and hourly rates incl. VAT?',
    orders: 'Can the repair order be signed on a tablet, with the mileage?',
    parts: 'Is stock updated when a part is fitted?',
    invoices: 'Are invoices ready for French e-invoicing (Factur-X)?',
    history: 'Can you find a vehicle’s history from its number plate?',
    reuse: 'Can the quote offer a reused part?',
    used: 'Can you track used vehicles and their refurbishment costs?',
    photos: 'Can you attach photos of the vehicle to the repair order?',
    export: 'Can you export your data (customers, vehicles, invoices) if you change software?',
  },
  market: {
    eyebrow: 'Budget to plan',
    priceRange: '€19 to €90',
    priceSuffix: 'per month, depending on modules and users',
    priceExamples: [
      { label: 'Gest’Garage', value: '€19/month' },
      { label: 'TDV', value: '€19.90 to €24.90/month incl. VAT' },
      { label: 'AutoProGestion', value: '€29 or €59/month' },
      { label: 'Kwixéo', value: '€22 to €89/month excl. VAT' },
    ],
    footnote:
      'Kwixéo costs €18.33 to €74.17 excl. VAT per month when paid yearly. EBP MéCa and GAD Garage are on quote.',
    footnoteLink: { label: 'See all prices', href: '#software' },
    adviceTitle: 'What to check before choosing',
    disclaimer: 'Public prices checked on 29 September 2026.',
    ctaLabel: 'Get free advice',
    leadFormTitle: 'Free advice to choose your software',
    leadFormIntro:
      'I reply within 24 hours to talk it through, by phone or video call. Your test answers are attached to your message.',
    leadBudget: 'Off-the-shelf software, €19 to €90 per month',
  },
  project: {
    eyebrow: 'Price range, fixed price',
    durationLabel: 'Timeline',
    maintenanceLabel: 'Maintenance',
    maintenanceValue: '€100 to €300/month',
    complementFootnote: 'Paid once, on top of your current subscription.',
    customFootnote: 'Paid once: the tool and its code belong to you.',
    adviceTitle: 'What to plan first',
    disclaimer: 'Indicative result. The final price is set in the quote.',
    ctaLabel: 'Get my estimate',
    leadFormTitle: 'Get my detailed estimate',
    leadFormIntro:
      'I reply within 24 hours with first ideas and a more precise budget. Your test answers are attached to your message.',
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'custom extension',
    customKind: 'custom tool',
  },
  results: {
    custom: {
      title: 'A custom tool for your garage',
      explanation:
        'At your size and with your own rules (service packages, hourly rates, workshops), off-the-shelf software makes you adapt to it. A tool designed for you follows the way you work and belongs to you. Your accounts stay in your accounting software, connected to the tool.',
    },
    complement: {
      title: 'Keep your software and add a custom extension',
      explanation:
        'Your software does the basics, there is no need to change it. A small tool plugged into it can handle what still takes up your time{pains}.',
      painsTemplate: ': {list}',
    },
    solo: {
      title: 'Off-the-shelf software is enough for you',
      explanation:
        'Working alone at the garage, software under €30 a month covers the essentials: quotes, repair orders, invoices and vehicle history. A custom tool would not pay off.',
      keepCurrentSentence: ' If yours suits you, keep it.',
    },
    market: {
      title: 'Off-the-shelf software is enough for now',
      explanation:
        'At your size, garage software on the market covers the essentials: bookings, quotes, repair orders, stock and invoices. A custom tool would cost you more than it would save you today.',
      unfitSentence: ' If yours does not suit you, compare two or three with the points below before switching.',
    },
  },
}
