import type { DibodevTradeQuizWording } from '~/core/types/DibodevTradeSoftwareQuiz'
import { NBSP } from '~/core/constants/typography'

export const AUTO_REPAIR_QUIZ_WORDING_ES: DibodevTradeQuizWording = {
  numberLocale: 'es-ES',
  quizName: '¿Qué software para tu taller mecánico?',
  questions: [
    {
      id: 'team',
      title: '¿Cuántas personas trabajan en el taller?',
      helpText: 'Mecánicos, recepción y tú incluidos.',
      leadMessageLabel: 'Equipo',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'persona', icon: null },
        { id: '2-4', label: '2 a 4', unit: 'personas', icon: null },
        { id: '5-10', label: '5 a 10', unit: 'personas', icon: null },
        { id: '10+', label: '+ de 10', unit: 'personas', icon: null },
      ],
    },
    {
      id: 'sites',
      title: '¿En cuántos talleres?',
      helpText: 'Cada dirección donde recibes vehículos.',
      leadMessageLabel: 'Talleres',
      display: 'tiles',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: '1', label: '1', unit: 'taller', icon: null },
        { id: '2-3', label: '2 o 3', unit: 'talleres', icon: null },
        { id: '4+', label: '4 o más', unit: 'talleres', icon: null },
      ],
    },
    {
      id: 'scope',
      title: '¿A qué te dedicas?',
      helpText: '',
      leadMessageLabel: 'Actividades',
      display: 'cards',
      selection: 'multiple',
      maxSelected: null,
      options: [
        { id: 'mechanics', label: 'Mecánica y mantenimiento', unit: '', icon: 'Wrench' },
        { id: 'body', label: 'Carrocería y pintura', unit: '', icon: 'SprayCan' },
        { id: 'tyres', label: 'Neumáticos y alineación', unit: '', icon: 'Disc' },
        { id: 'used', label: 'Venta de vehículos de segunda mano', unit: '', icon: 'Car' },
      ],
    },
    {
      id: 'pains',
      title: '¿Qué es lo que más tiempo te quita?',
      helpText: '',
      leadMessageLabel: 'Lo que quita tiempo',
      display: 'list',
      selection: 'multiple',
      maxSelected: 3,
      options: [
        { id: 'booking', label: 'Dar citas por teléfono', unit: '', icon: null },
        { id: 'quotes', label: 'Hacer los presupuestos (piezas y mano de obra)', unit: '', icon: null },
        { id: 'orders', label: 'Rellenar las órdenes de reparación', unit: '', icon: null },
        { id: 'parts', label: 'Pedir las piezas y seguir el stock', unit: '', icon: null },
        { id: 'invoices', label: 'Hacer las facturas y reclamar los impagos', unit: '', icon: null },
        { id: 'history', label: 'Encontrar el historial de un vehículo', unit: '', icon: null },
        { id: 'reuse', label: 'Ofrecer piezas de reutilización', unit: '', icon: null },
        { id: 'used', label: 'Seguir los vehículos de segunda mano en venta', unit: '', icon: null },
      ],
    },
    {
      id: 'current',
      title: '¿Ya usas un software de taller?',
      helpText: '',
      leadMessageLabel: 'Software actual',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'none', label: 'No, papel, Excel o Word', unit: '', icon: 'FileSpreadsheet' },
        { id: 'unfit', label: 'Sí, pero no se adapta a nuestra forma de trabajar', unit: '', icon: 'AlertCircle' },
        { id: 'fit', label: 'Sí, y nos va bien', unit: '', icon: 'CheckCircle' },
      ],
    },
    {
      id: 'priority',
      title: '¿Qué es lo más importante para ti?',
      helpText: '',
      leadMessageLabel: 'Prioridad',
      display: 'cards',
      selection: 'single',
      maxSelected: null,
      options: [
        { id: 'budget', label: 'Empezar rápido, con poco presupuesto', unit: '', icon: 'Zap' },
        { id: 'simple', label: 'Una herramienta sencilla para el taller', unit: '', icon: 'Smile' },
        {
          id: 'rules',
          label: 'Una herramienta que siga nuestras tarifas, precios por hora y talleres',
          unit: '',
          icon: 'SlidersHorizontal',
        },
        {
          id: 'ownership',
          label: 'Dejar de depender de una suscripción y conservar nuestros datos',
          unit: '',
          icon: 'KeyRound',
        },
      ],
    },
  ],
  conjunction: 'y',
  priceRangeTemplate: `{min} a {max}${NBSP}€`,
  weeksRangeTemplate: '{min} a {max} semanas',
  recapTeamWords: {
    '1': 'una sola persona',
    '2-4': '2 a 4 personas',
    '5-10': '5 a 10 personas',
    '10+': 'más de 10 personas',
  },
  recapSitesWords: { '1': 'un solo taller', '2-3': '2 o 3 talleres', '4+': '4 talleres o más' },
  recapScopeWords: { mechanics: 'mecánica', body: 'carrocería', tyres: 'neumáticos', used: 'segunda mano' },
  recapScopeTemplate: '{items}',
  complementPainWords: {
    booking: 'las citas',
    quotes: 'los presupuestos',
    orders: 'las órdenes de reparación',
    parts: 'las piezas',
    invoices: 'las facturas',
    history: 'el historial de los vehículos',
    reuse: 'las piezas de reutilización',
    used: 'los vehículos de segunda mano',
  },
  features: {
    booking: 'Citas en línea, en tu web, según el espacio real en el taller',
    quotes: 'Presupuestos en pocos clics, con tus tarifas, tus precios por hora y tus piezas',
    orders:
      'El presupuesto aceptado convertido en orden de reparación firmada y luego en factura, sin volver a escribir',
    parts: 'Las piezas pedidas para cada intervención, y el stock actualizado al montarlas',
    invoices: 'Facturas conformes enviadas al momento, con recordatorio automático de los impagos',
    history: 'El historial de cada vehículo (intervenciones, kilometraje, piezas) encontrado por su matrícula',
    reuse: 'Una pieza de reutilización propuesta en el presupuesto cuando la reparación lo permite',
    used: 'Los vehículos de segunda mano seguidos desde la recompra hasta la venta, con sus gastos',
    photos: 'Las fotos del vehículo a su llegada, adjuntas a la orden de reparación',
    multiSite: 'La agenda y el stock de cada taller, y los traslados de piezas entre talleres',
  },
  checks: {
    primary: '¿El presupuesto se convierte en orden de reparación y luego en factura, sin volver a escribir nada?',
    booking: '¿Tus clientes pueden pedir cita en línea, en tu web?',
    quotes: '¿Se pueden guardar tus tarifas y tus precios por hora con IVA?',
    orders: '¿La orden de reparación se firma en una tableta, con el kilometraje?',
    parts: '¿El stock se actualiza al montar una pieza?',
    invoices: '¿Las facturas están listas para la factura electrónica francesa (Factur-X)?',
    history: '¿Se encuentra el historial de un vehículo por su matrícula?',
    reuse: '¿El presupuesto permite proponer una pieza de reutilización?',
    used: '¿Se pueden seguir los vehículos de segunda mano y sus gastos de puesta a punto?',
    photos: '¿Se pueden adjuntar fotos del vehículo a la orden de reparación?',
    export: '¿Puedes exportar tus datos (clientes, vehículos, facturas) si cambias de software?',
  },
  market: {
    eyebrow: 'Presupuesto a prever',
    priceRange: `19 a 90${NBSP}€`,
    priceSuffix: 'al mes, según los módulos y los usuarios',
    priceExamples: [
      { label: 'Gest’Garage', value: `19${NBSP}€/mes` },
      { label: 'TDV', value: `19,90 a 24,90${NBSP}€/mes con IVA` },
      { label: 'AutoProGestion', value: `29 o 59${NBSP}€/mes` },
      { label: 'Kwixéo', value: `22 a 89${NBSP}€/mes sin IVA` },
    ],
    footnote: `Kwixéo cuesta de 18,33 a 74,17${NBSP}€ sin IVA al mes con pago anual. EBP MéCa y GAD Garage funcionan con presupuesto.`,
    footnoteLink: { label: 'Ver todos los precios', href: '#programas' },
    adviceTitle: 'Qué comprobar antes de elegir',
    disclaimer: 'Precios públicos consultados el 29 de septiembre de 2026.',
    ctaLabel: 'Pedir consejo gratis',
    leadFormTitle: 'Un consejo gratuito para elegir tu software',
    leadFormIntro: `Te respondo en 24${NBSP}h para hablarlo, por teléfono o videollamada. Tus respuestas al test se adjuntan a tu mensaje.`,
    leadBudget: `Software del mercado, 19 a 90${NBSP}€ al mes`,
  },
  project: {
    eyebrow: 'Orden de precio, a precio cerrado',
    durationLabel: 'Plazo',
    maintenanceLabel: 'Mantenimiento',
    maintenanceValue: `100 a 300${NBSP}€/mes`,
    complementFootnote: 'Se paga una sola vez, además de tu suscripción actual.',
    customFootnote: 'Se paga una sola vez: la herramienta y su código son tuyos.',
    adviceTitle: 'Qué prever primero',
    disclaimer: 'Resultado orientativo. El precio final se fija en el presupuesto.',
    ctaLabel: 'Recibir mi estimación',
    leadFormTitle: 'Recibir mi estimación detallada',
    leadFormIntro: `Te respondo en 24${NBSP}h con primeras ideas y un presupuesto más preciso. Tus respuestas al test se adjuntan a tu mensaje.`,
    leadBudgetTemplate: '{range} ({kind})',
    complementKind: 'complemento a medida',
    customKind: 'herramienta a medida',
  },
  results: {
    custom: {
      title: 'Una herramienta a medida para tu taller',
      explanation:
        'Con tu tamaño y tus propias reglas (tarifas, precios por hora, talleres), los programas del mercado te obligan a adaptarte a ellos. Una herramienta diseñada para ti sigue tu forma de trabajar y es tuya. Tu contabilidad sigue en tu programa contable, conectado a la herramienta.',
    },
    complement: {
      title: 'Conserva tu software y añade un complemento a medida',
      explanation:
        'Tu software hace el trabajo básico, no hace falta cambiarlo. Una pequeña herramienta conectada a él puede resolver lo que aún te quita tiempo{pains}.',
      painsTemplate: ': {list}',
    },
    solo: {
      title: 'Te basta con un software del mercado',
      explanation: `Si trabajas solo en el taller, un software de menos de 30${NBSP}€ al mes cubre lo esencial: presupuestos, órdenes de reparación, facturas e historial de los vehículos. Una herramienta a medida no sería rentable.`,
      keepCurrentSentence: ' Si el tuyo te va bien, consérvalo.',
    },
    market: {
      title: 'Por ahora te basta con un software del mercado',
      explanation:
        'Con tu tamaño, los programas de taller del mercado cubren lo esencial: citas, presupuestos, órdenes de reparación, stock y facturas. Una herramienta a medida te costaría hoy más de lo que te haría ganar.',
      unfitSentence: ' Si el tuyo no te convence, compara dos o tres con los puntos de abajo antes de cambiar.',
    },
  },
}
